/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.waveprotocol.box.server.rpc;

import org.json.JSONObject;

/**
 * Pure-Java replacement for the 9 GXP templates formerly generated by
 * {@code com.google.gxp}. Each public static method returns a complete HTML
 * page (or fragment) as a {@link String}.
 *
 * <p>Auth/registration pages use a modern centered-card CSS layout. The wave
 * client page preserves the original structure required by the GWT webclient.
 */
public final class HtmlRenderer {

  private HtmlRenderer() {} // utility class

  // =========================================================================
  // Wave Theme Constants
  // =========================================================================

  private static final String WAVE_PRIMARY = "#0077b6";
  private static final String WAVE_ACCENT = "#00b4d8";
  private static final String WAVE_LIGHT = "#90e0ef";
  private static final String WAVE_GRADIENT = "linear-gradient(135deg, #0077b6 0%, #00b4d8 50%, #90e0ef 100%)";
  private static final String WAVE_BG = "#f0f4f8";
  private static final String WAVE_BORDER = "#e2e8f0";
  private static final String WAVE_TEXT = "#1a202c";
  private static final String WAVE_TEXT_MUTED = "#718096";
  private static final String WAVE_FONT =
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', Arial, sans-serif";

  // =========================================================================
  // Wave Panel CSS (ocean theme for GWT client panels)
  // =========================================================================

  /**
   * Comprehensive CSS overrides for the GWT webclient panels. Uses stable
   * {@code [kind="X"]} attribute selectors because GWT obfuscates class names.
   * All rules are scoped under {@code #app} to avoid leaking into auth pages.
   */
  private static final String WAVE_PANEL_CSS =
      "\n/* ===== SupaWave Panel Theme ===== */\n"

      // --- Global / App container ---
      + "#app {\n"
      + "  font-family: " + WAVE_FONT + ";\n"
      + "  background: " + WAVE_BG + ";\n"
      + "  color: " + WAVE_TEXT + ";\n"
      + "}\n"

      // --- Split panel dragger ---
      + ".gwt-SplitLayoutPanel-HDragger {\n"
      + "  background: " + WAVE_BG + " !important;\n"
      + "  width: 6px !important;\n"
      + "  cursor: col-resize;\n"
      + "}\n"
      + ".gwt-SplitLayoutPanel-VDragger {\n"
      + "  background: " + WAVE_BG + " !important;\n"
      + "  height: 6px !important;\n"
      + "  cursor: row-resize;\n"
      + "}\n"

      // --- Search panel (left sidebar) ---
      // Search area header bar
      + "#app [kind=\"c\"] { background: #fff; }\n"

      // Search input
      + "#app input[type=\"search\"],\n"
      + "#app input[type=\"text\"] {\n"
      + "  border: 1.5px solid " + WAVE_BORDER + ";\n"
      + "  border-radius: 20px;\n"
      + "  padding: 6px 14px;\n"
      + "  font-size: 13px;\n"
      + "  font-family: " + WAVE_FONT + ";\n"
      + "  outline: none;\n"
      + "  transition: border-color 0.2s, box-shadow 0.2s;\n"
      + "  background: #fff;\n"
      + "}\n"
      + "#app input[type=\"search\"]:focus,\n"
      + "#app input[type=\"text\"]:focus {\n"
      + "  border-color: " + WAVE_PRIMARY + ";\n"
      + "  box-shadow: 0 0 0 3px rgba(0,119,182,0.10);\n"
      + "}\n"

      // Filter buttons (Shared / All / Inbox)
      + "#app .gwt-Button {\n"
      + "  border: 1.5px solid " + WAVE_BORDER + ";\n"
      + "  border-radius: 16px;\n"
      + "  background: #fff;\n"
      + "  color: " + WAVE_TEXT_MUTED + ";\n"
      + "  font-family: " + WAVE_FONT + ";\n"
      + "  font-size: 12px;\n"
      + "  font-weight: 500;\n"
      + "  padding: 4px 14px;\n"
      + "  cursor: pointer;\n"
      + "  transition: all 0.15s ease;\n"
      + "  line-height: 1.4;\n"
      + "}\n"
      + "#app .gwt-Button:hover {\n"
      + "  border-color: " + WAVE_PRIMARY + ";\n"
      + "  color: " + WAVE_PRIMARY + ";\n"
      + "  background: rgba(0,119,182,0.04);\n"
      + "}\n"

      // --- Digest list items (wave inbox) ---
      // Digest items have a `di` attribute
      + "#app [di] {\n"
      + "  border-bottom: 1px solid " + WAVE_BORDER + ";\n"
      + "  padding: 10px 12px;\n"
      + "  cursor: pointer;\n"
      + "  transition: background 0.15s ease;\n"
      + "  background: #fff;\n"
      + "  font-family: " + WAVE_FONT + ";\n"
      + "  color: " + WAVE_TEXT_MUTED + ";\n"
      + "}\n"
      + "#app [di]:hover {\n"
      + "  background: rgba(144,224,239,0.12);\n"
      + "}\n"
      // Selected digest
      + "#app [di].SWCa-b {\n"
      + "  background: " + WAVE_PRIMARY + " !important;\n"
      + "  color: #fff !important;\n"
      + "}\n"
      // Also handle via more generic attribute approach - the selected class
      // is dynamically added. We target any digest with white color override:
      + "#app [di][class*=\"selected\"] {\n"
      + "  background: " + WAVE_PRIMARY + " !important;\n"
      + "  color: #fff !important;\n"
      + "}\n"

      // Digest avatars - round
      + "#app [di] img {\n"
      + "  border-radius: 50%;\n"
      + "  border-color: " + WAVE_BORDER + ";\n"
      + "}\n"

      // Unread count badge
      + "#app [di] span[class*=\"unreadCount\"],\n"
      + "#app [di] span[style*=\"border-radius\"] {\n"
      + "  background-color: " + WAVE_ACCENT + " !important;\n"
      + "  border: none !important;\n"
      + "  color: #fff !important;\n"
      + "  font-size: 11px;\n"
      + "  font-weight: 600;\n"
      + "  padding: 1px 8px;\n"
      + "  border-radius: 10px;\n"
      + "}\n"

      // Digest title - unread bold
      + "#app [di] span[class*=\"unread\"] {\n"
      + "  color: " + WAVE_TEXT + ";\n"
      + "  font-weight: 600;\n"
      + "}\n"

      // --- Participants panel ---
      + "#app [kind=\"s\"] {\n"
      + "  background: linear-gradient(180deg, #e8f4f8 0%, #fff 100%) !important;\n"
      + "  border-bottom: 1px solid " + WAVE_BORDER + " !important;\n"
      + "  border-left: none !important;\n"
      + "  padding-bottom: 6px;\n"
      + "}\n"
      // Participant avatars - round
      + "#app [kind=\"s\"] img[kind=\"p\"],\n"
      + "#app [kind=\"s\"] img {\n"
      + "  border-radius: 50%;\n"
      + "  border: 2px solid #fff;\n"
      + "  box-shadow: 0 1px 3px rgba(0,0,0,0.1);\n"
      + "  transition: transform 0.15s ease;\n"
      + "}\n"
      + "#app [kind=\"s\"] img:hover {\n"
      + "  transform: scale(1.08);\n"
      + "}\n"
      // Add participant button
      + "#app [kind=\"a\"] {\n"
      + "  cursor: pointer;\n"
      + "  opacity: 0.7;\n"
      + "  transition: opacity 0.15s ease;\n"
      + "}\n"
      + "#app [kind=\"a\"]:hover {\n"
      + "  opacity: 1;\n"
      + "}\n"

      // --- New Wave With Participants button ---
      + "#app [kind=\"npw\"] {\n"
      + "  background: " + WAVE_PRIMARY + " !important;\n"
      + "  color: #fff !important;\n"
      + "  border: none !important;\n"
      + "  border-radius: 20px !important;\n"
      + "  padding: 5px 16px !important;\n"
      + "  font-family: " + WAVE_FONT + ";\n"
      + "  font-size: 12px;\n"
      + "  font-weight: 600;\n"
      + "  cursor: pointer;\n"
      + "  transition: background 0.2s ease, box-shadow 0.2s ease;\n"
      + "  display: inline-block;\n"
      + "  text-align: center;\n"
      + "  line-height: 1.6;\n"
      + "  box-shadow: 0 1px 3px rgba(0,119,182,0.2);\n"
      + "  width: auto !important;\n"
      + "  margin: 4px 5px !important;\n"
      + "}\n"
      + "#app [kind=\"npw\"]:hover {\n"
      + "  background: #005f8f !important;\n"
      + "  box-shadow: 0 3px 8px rgba(0,119,182,0.3);\n"
      + "}\n"

      // --- Blips ---
      + "#app [kind=\"b\"] {\n"
      + "  position: relative;\n"
      + "  font-family: " + WAVE_FONT + ";\n"
      + "}\n"

      // Blip meta area
      + "#app [kind=\"m\"] {\n"
      + "  font-family: " + WAVE_FONT + ";\n"
      + "}\n"
      // Blip avatar - round
      + "#app [kind=\"m\"] img {\n"
      + "  border-radius: 50%;\n"
      + "  border: 2px solid #fff;\n"
      + "  box-shadow: 0 1px 2px rgba(0,0,0,0.08);\n"
      + "}\n"

      // Metabar - override the green/gray scheme
      // Read state: light gray-blue
      + "#app [kind=\"m\"] > div:first-child + div {\n"
      + "  border-radius: 6px;\n"
      + "  transition: all 200ms ease;\n"
      + "}\n"

      // --- Focus frame (selected blip border) ---
      // The focus frame is rendered as an absolutely positioned div.
      // We can't target it by kind, but it has specific border styles
      // that we can override via the GWT class patterns.
      // Border color from green (rgb(114,135,27)) to ocean blue:
      + "#app div[style*=\"border\"][style*=\"rgb(114, 135, 27)\"],\n"
      + "#app div[style*=\"border\"][style*=\"rgb(114,135,27)\"] {\n"
      + "  border-color: " + WAVE_PRIMARY + " !important;\n"
      + "}\n"

      // --- Menu items (Edit, Reply, Delete, Link) ---
      + "#app [kind=\"i\"] {\n"
      + "  font-family: " + WAVE_FONT + ";\n"
      + "  font-size: 12px;\n"
      + "  color: " + WAVE_TEXT_MUTED + ";\n"
      + "  padding: 3px 6px;\n"
      + "  border-radius: 4px;\n"
      + "  cursor: pointer;\n"
      + "  transition: all 0.15s ease;\n"
      + "}\n"
      + "#app [kind=\"i\"]:hover {\n"
      + "  color: " + WAVE_PRIMARY + ";\n"
      + "  background: rgba(0,119,182,0.06);\n"
      + "}\n"

      // --- Reply box ---
      + "#app [kind=\"rb\"] {\n"
      + "  background: " + WAVE_BG + " !important;\n"
      + "  border: 1.5px dashed " + WAVE_BORDER + " !important;\n"
      + "  border-radius: 8px !important;\n"
      + "  color: " + WAVE_TEXT_MUTED + ";\n"
      + "  font-family: " + WAVE_FONT + ";\n"
      + "  font-size: 13px;\n"
      + "  padding: 8px 12px !important;\n"
      + "  transition: all 0.2s ease;\n"
      + "}\n"
      + "#app [kind=\"rb\"]:hover {\n"
      + "  border-color: " + WAVE_ACCENT + " !important;\n"
      + "  background: rgba(0,180,216,0.04) !important;\n"
      + "  color: " + WAVE_PRIMARY + ";\n"
      + "}\n"
      + "#app [kind=\"rb\"] img {\n"
      + "  border-radius: 50%;\n"
      + "}\n"

      // --- Inline thread toggle (collapse/expand) ---
      + "#app [kind=\"g\"] {\n"
      + "  font-family: " + WAVE_FONT + ";\n"
      + "  font-size: 12px;\n"
      + "}\n"

      // Continuation indicator bar
      + "#app [kind=\"ci\"] {\n"
      + "  transition: opacity 0.2s ease;\n"
      + "}\n"

      // --- Conversation scroll area ---
      // Scrollbar styling for webkit browsers
      + "#app ::-webkit-scrollbar {\n"
      + "  width: 8px;\n"
      + "}\n"
      + "#app ::-webkit-scrollbar-track {\n"
      + "  background: " + WAVE_BG + ";\n"
      + "}\n"
      + "#app ::-webkit-scrollbar-thumb {\n"
      + "  background: #c4cdd5;\n"
      + "  border-radius: 4px;\n"
      + "}\n"
      + "#app ::-webkit-scrollbar-thumb:hover {\n"
      + "  background: #a0aec0;\n"
      + "}\n"

      // --- Popup / Dialog overrides ---
      // Popups have z-index:1000 and position:absolute
      + "#app .gwt-PopupPanel,\n"
      + "body > .gwt-PopupPanel {\n"
      + "  border-radius: 10px;\n"
      + "  box-shadow: 0 4px 20px rgba(0,0,0,0.12), 0 1px 4px rgba(0,0,0,0.06);\n"
      + "  border: 1px solid " + WAVE_BORDER + ";\n"
      + "}\n"

      // --- Profile popup card ---
      + "#app .gwt-PopupPanel img,\n"
      + "body > .gwt-PopupPanel img {\n"
      + "  border-radius: 50%;\n"
      + "}\n"

      // --- Toolbar (edit toolbar, formatting bar) ---
      + "#app .gwt-ToggleButton,\n"
      + "#app .gwt-PushButton {\n"
      + "  border-radius: 4px;\n"
      + "  transition: background 0.1s ease;\n"
      + "}\n"

      // --- Loading animation colors ---
      // Override the pulsing placeholder from #EEE to themed
      + "@keyframes supawave-pulse {\n"
      + "  0% { background-color: #f0f4f8; }\n"
      + "  50% { background-color: #e2e8f0; }\n"
      + "  100% { background-color: #f0f4f8; }\n"
      + "}\n"

      // --- Show More button in search results ---
      + "#app div[style*=\"visibility\"][style*=\"hidden\"] ~ div,\n"
      + "#app div[style*=\"cursor: pointer\"][style*=\"text-align: center\"] {\n"
      + "  font-family: " + WAVE_FONT + ";\n"
      + "  color: " + WAVE_PRIMARY + ";\n"
      + "}\n"

      // --- General link styling inside app ---
      + "#app a {\n"
      + "  color: " + WAVE_PRIMARY + ";\n"
      + "  text-decoration: none;\n"
      + "}\n"
      + "#app a:hover {\n"
      + "  text-decoration: underline;\n"
      + "}\n"

      // --- Selection highlight ---
      + "#app ::selection {\n"
      + "  background: rgba(0,180,216,0.2);\n"
      + "}\n"

      + "/* ===== End SupaWave Panel Theme ===== */\n";

  // =========================================================================
  // Animated wave SVG (reusable across pages)
  // =========================================================================

  private static final String WAVE_SVG =
      "<div class=\"wave-bg\">\n"
      + "  <svg viewBox=\"0 0 1440 150\" preserveAspectRatio=\"none\">\n"
      + "    <path d=\"M0,50 C360,150 1080,-50 1440,50 L1440,150 L0,150 Z\" fill=\"rgba(0,119,182,0.15)\">\n"
      + "      <animate attributeName=\"d\" dur=\"8s\" repeatCount=\"indefinite\"\n"
      + "        values=\"M0,50 C360,150 1080,-50 1440,50 L1440,150 L0,150 Z;\n"
      + "                M0,80 C360,-20 1080,120 1440,30 L1440,150 L0,150 Z;\n"
      + "                M0,50 C360,150 1080,-50 1440,50 L1440,150 L0,150 Z\"/>\n"
      + "    </path>\n"
      + "    <path d=\"M0,80 C480,0 960,120 1440,40 L1440,150 L0,150 Z\" fill=\"rgba(0,180,216,0.10)\">\n"
      + "      <animate attributeName=\"d\" dur=\"10s\" repeatCount=\"indefinite\"\n"
      + "        values=\"M0,80 C480,0 960,120 1440,40 L1440,150 L0,150 Z;\n"
      + "                M0,40 C480,120 960,0 1440,80 L1440,150 L0,150 Z;\n"
      + "                M0,80 C480,0 960,120 1440,40 L1440,150 L0,150 Z\"/>\n"
      + "    </path>\n"
      + "    <path d=\"M0,100 C320,60 720,130 1440,70 L1440,150 L0,150 Z\" fill=\"rgba(144,224,239,0.08)\">\n"
      + "      <animate attributeName=\"d\" dur=\"12s\" repeatCount=\"indefinite\"\n"
      + "        values=\"M0,100 C320,60 720,130 1440,70 L1440,150 L0,150 Z;\n"
      + "                M0,70 C320,130 720,60 1440,100 L1440,150 L0,150 Z;\n"
      + "                M0,100 C320,60 720,130 1440,70 L1440,150 L0,150 Z\"/>\n"
      + "    </path>\n"
      + "  </svg>\n"
      + "</div>\n";

  // =========================================================================
  // Wave logo SVG (inline, no external file dependency)
  // =========================================================================

  private static final String WAVE_LOGO_SVG =
      "<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"
      + "  <circle cx=\"24\" cy=\"24\" r=\"24\" fill=\"" + WAVE_PRIMARY + "\"/>\n"
      + "  <path d=\"M10 28 Q16 16 22 28 Q28 40 34 28 Q38 20 38 20\" "
      + "stroke=\"white\" stroke-width=\"3\" stroke-linecap=\"round\" fill=\"none\">\n"
      + "    <animate attributeName=\"d\" dur=\"3s\" repeatCount=\"indefinite\"\n"
      + "      values=\"M10 28 Q16 16 22 28 Q28 40 34 28 Q38 20 38 20;\n"
      + "              M10 24 Q16 36 22 24 Q28 12 34 24 Q38 30 38 30;\n"
      + "              M10 28 Q16 16 22 28 Q28 40 34 28 Q38 20 38 20\"/>\n"
      + "  </path>\n"
      + "</svg>\n";

  /** Smaller 28px version of the wave logo for the in-app top bar. */
  private static final String WAVE_LOGO_SVG_SMALL =
      "<svg width=\"28\" height=\"28\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" style=\"vertical-align:middle;\">\n"
      + "  <circle cx=\"24\" cy=\"24\" r=\"24\" fill=\"" + WAVE_PRIMARY + "\"/>\n"
      + "  <path d=\"M10 28 Q16 16 22 28 Q28 40 34 28 Q38 20 38 20\" "
      + "stroke=\"white\" stroke-width=\"3\" stroke-linecap=\"round\" fill=\"none\">\n"
      + "    <animate attributeName=\"d\" dur=\"3s\" repeatCount=\"indefinite\"\n"
      + "      values=\"M10 28 Q16 16 22 28 Q28 40 34 28 Q38 20 38 20;\n"
      + "              M10 24 Q16 36 22 24 Q28 12 34 24 Q38 30 38 30;\n"
      + "              M10 28 Q16 16 22 28 Q28 40 34 28 Q38 20 38 20\"/>\n"
      + "  </path>\n"
      + "</svg>";

  // =========================================================================
  // Shared CSS for auth-style pages (login, registration, robot registration)
  // =========================================================================

  private static final String AUTH_CSS =
      "<style>\n"
      + "*, *::before, *::after { box-sizing: border-box; }\n"
      + "body {\n"
      + "  margin: 0; padding: 0;\n"
      + "  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,\n"
      + "    Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', Arial, sans-serif;\n"
      + "  background: " + WAVE_GRADIENT + ";\n"
      + "  color: #333;\n"
      + "  min-height: 100vh;\n"
      + "}\n"
      + ".wave-bg {\n"
      + "  position: fixed; bottom: 0; left: 0; width: 100%; height: 180px; z-index: 0;\n"
      + "  pointer-events: none;\n"
      + "}\n"
      + ".wave-bg svg { width: 100%; height: 100%; }\n"
      + ".page-wrapper {\n"
      + "  position: relative; z-index: 1;\n"
      + "  display: flex; flex-direction: column; align-items: center;\n"
      + "  min-height: 100vh; padding: 40px 16px 200px;\n"
      + "}\n"
      + ".brand {\n"
      + "  text-align: center; margin-bottom: 24px;\n"
      + "}\n"
      + ".brand svg { margin-bottom: 8px; }\n"
      + ".brand-name {\n"
      + "  font-size: 28px; font-weight: 700; color: #fff;\n"
      + "  letter-spacing: -0.5px;\n"
      + "}\n"
      + ".card {\n"
      + "  width: 100%; max-width: 420px; padding: 32px 28px;\n"
      + "  background: #fff;\n"
      + "  border-radius: 12px;\n"
      + "  box-shadow: 0 8px 32px rgba(0,0,0,0.12), 0 2px 8px rgba(0,0,0,0.08);\n"
      + "}\n"
      + ".card h1 {\n"
      + "  font-size: 22px; margin: 0 0 6px; font-weight: 600; color: #1a1a2e;\n"
      + "}\n"
      + ".card .subtitle {\n"
      + "  font-size: 14px; color: #666; margin-bottom: 20px;\n"
      + "}\n"
      + "label { display: block; font-size: 14px; font-weight: 500; margin-bottom: 4px; color: #444; }\n"
      + ".input-group {\n"
      + "  display: flex; align-items: center; margin-bottom: 14px;\n"
      + "}\n"
      + ".input-group input {\n"
      + "  flex: 1; padding: 10px 12px; font-size: 14px;\n"
      + "  border: 1.5px solid #d0d5dd; border-radius: 8px;\n"
      + "  outline: none; transition: border-color 0.2s, box-shadow 0.2s;\n"
      + "  background: #fafbfc;\n"
      + "}\n"
      + ".input-group input:focus {\n"
      + "  border-color: " + WAVE_PRIMARY + ";\n"
      + "  box-shadow: 0 0 0 3px rgba(0,119,182,0.12);\n"
      + "  background: #fff;\n"
      + "}\n"
      + ".input-group .domain-suffix {\n"
      + "  margin-left: 8px; font-size: 13px; color: #666; white-space: nowrap;\n"
      + "}\n"
      + "input[type=text], input[type=password] {\n"
      + "  width: 100%; padding: 10px 12px; font-size: 14px;\n"
      + "  border: 1.5px solid #d0d5dd; border-radius: 8px;\n"
      + "  outline: none; transition: border-color 0.2s, box-shadow 0.2s;\n"
      + "  margin-bottom: 14px; background: #fafbfc;\n"
      + "}\n"
      + "input[type=text]:focus, input[type=password]:focus {\n"
      + "  border-color: " + WAVE_PRIMARY + ";\n"
      + "  box-shadow: 0 0 0 3px rgba(0,119,182,0.12);\n"
      + "  background: #fff;\n"
      + "}\n"
      + ".btn-primary {\n"
      + "  display: inline-block; padding: 11px 28px;\n"
      + "  background: " + WAVE_PRIMARY + "; color: #fff; border: none; border-radius: 8px;\n"
      + "  font-size: 14px; font-weight: 600; cursor: pointer;\n"
      + "  transition: background 0.2s, transform 0.1s, box-shadow 0.2s;\n"
      + "}\n"
      + ".btn-primary:hover {\n"
      + "  background: #005f8f;\n"
      + "  box-shadow: 0 4px 12px rgba(0,119,182,0.3);\n"
      + "}\n"
      + ".btn-primary:active { transform: translateY(1px); }\n"
      + ".btn-secondary {\n"
      + "  display: inline-block; padding: 11px 28px;\n"
      + "  background: #fff; color: " + WAVE_PRIMARY + "; border: 1.5px solid " + WAVE_PRIMARY + "; border-radius: 8px;\n"
      + "  font-size: 14px; font-weight: 600; cursor: pointer; margin-right: 8px;\n"
      + "  transition: background 0.2s;\n"
      + "}\n"
      + ".btn-secondary:hover { background: #f0f8ff; }\n"
      + ".msg { font-size: 13px; min-height: 18px; margin-bottom: 10px; }\n"
      + ".msg.error { color: #d93025; }\n"
      + ".msg.success { color: #188038; }\n"
      + ".footer-link { font-size: 13px; margin-top: 16px; text-align: center; }\n"
      + ".footer-link a { color: " + WAVE_PRIMARY + "; text-decoration: none; font-weight: 500; }\n"
      + ".footer-link a:hover { text-decoration: underline; }\n"
      + ".buttons { display: flex; gap: 8px; margin-top: 8px; }\n"
      + "@media (max-width: 480px) {\n"
      + "  .page-wrapper { padding: 24px 12px 180px; }\n"
      + "  .card { padding: 24px 20px; }\n"
      + "  .brand-name { font-size: 24px; }\n"
      + "}\n"
      + "</style>\n";

  // =========================================================================
  // 1. Authentication (Login) Page
  // =========================================================================

  /**
   * Renders the login page.
   *
   * @param domain              the wave server domain (e.g. "example.com")
   * @param message             status message to display (may be empty)
   * @param responseType        one of "NONE", "FAILED", "SUCCESS"
   * @param disableLoginPage    if true, show a disabled-auth notice instead of the form
   * @param analyticsAccount    Google Analytics account ID (may be null/empty)
   */
  public static String renderAuthenticationPage(String domain, String message,
      String responseType, boolean disableLoginPage, String analyticsAccount) {
    return renderAuthenticationPage(domain, message, responseType, disableLoginPage,
        analyticsAccount, false, false);
  }

  /**
   * Renders the login page with optional email auth links.
   *
   * @param domain              the wave server domain (e.g. "example.com")
   * @param message             status message to display (may be empty)
   * @param responseType        one of "NONE", "FAILED", "SUCCESS"
   * @param disableLoginPage    if true, show a disabled-auth notice instead of the form
   * @param analyticsAccount    Google Analytics account ID (may be null/empty)
   * @param passwordResetEnabled whether to show "Forgot password?" link
   * @param magicLinkEnabled     whether to show "Login with email" link
   */
  public static String renderAuthenticationPage(String domain, String message,
      String responseType, boolean disableLoginPage, String analyticsAccount,
      boolean passwordResetEnabled, boolean magicLinkEnabled) {
    StringBuilder sb = new StringBuilder(8192);
    sb.append("<!DOCTYPE html>\n<html dir=\"ltr\">\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append("<title>Sign In - SupaWave</title>\n");
    sb.append(AUTH_CSS);
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body onload=\"init()\">\n");

    sb.append(WAVE_SVG);
    sb.append("<div class=\"page-wrapper\">\n");
    sb.append("  <div class=\"brand\">\n");
    sb.append("    ").append(WAVE_LOGO_SVG);
    sb.append("    <div class=\"brand-name\">SupaWave</div>\n");
    sb.append("  </div>\n");

    sb.append("  <div class=\"card\">\n");
    sb.append("    <h1>Sign In</h1>\n");
    sb.append("    <div class=\"subtitle\">@").append(escapeHtml(domain)).append("</div>\n");

    if (disableLoginPage) {
      sb.append("    <p>HTTP authentication disabled by administrator. "
          + "Install and use your certificate instead.</p>\n");
    } else {
      sb.append("    <form id=\"wiab_loginform\" action=\"\" method=\"post\">\n");
      sb.append("      <label for=\"address\">Username</label>\n");
      sb.append("      <div class=\"input-group\">\n");
      sb.append("        <input type=\"text\" name=\"address\" id=\"address\" autocomplete=\"username\" placeholder=\"your.name\">\n");
      sb.append("        <span class=\"domain-suffix\">@").append(escapeHtml(domain)).append("</span>\n");
      sb.append("      </div>\n");
      sb.append("      <label for=\"password\">Password</label>\n");
      sb.append("      <input type=\"password\" name=\"password\" id=\"password\" autocomplete=\"current-password\" placeholder=\"Enter your password\">\n");
      sb.append("      <div class=\"msg\" id=\"messageLbl\"></div>\n");
      sb.append("      <input type=\"submit\" class=\"btn-primary\" name=\"signIn\" id=\"signIn\" value=\"Sign in\" style=\"width:100%;\">\n");
      sb.append("    </form>\n");
      if (passwordResetEnabled) {
        sb.append("    <div class=\"footer-link\">\n");
        sb.append("      <a href=\"/auth/password-reset\">Forgot password?</a>\n");
        sb.append("    </div>\n");
      }
      if (magicLinkEnabled) {
        sb.append("    <div class=\"footer-link\">\n");
        sb.append("      <a href=\"/auth/magic-link\">Login with email link</a>\n");
        sb.append("    </div>\n");
      }
      sb.append("    <div class=\"footer-link\">\n");
      sb.append("      Don't have an account? <a href=\"/auth/register\">Register</a>\n");
      sb.append("    </div>\n");
    }
    sb.append("  </div>\n"); // .card
    sb.append("</div>\n"); // .page-wrapper

    sb.append("<script>\n");
    sb.append("var RESPONSE_STATUS_NONE = \"NONE\";\n");
    sb.append("var RESPONSE_STATUS_FAILED = \"FAILED\";\n");
    sb.append("var RESPONSE_STATUS_SUCCESS = \"SUCCESS\";\n");
    sb.append("var message = ").append(escapeJsonString(message)).append(";\n");
    sb.append("var responseType = ").append(escapeJsonString(responseType)).append(";\n");
    sb.append("function init() { setFocus(); handleResponse(responseType, message); }\n");
    sb.append("function setFocus() { var el = document.getElementById(\"address\"); if (el) el.focus(); }\n");
    sb.append("function handleResponse(rt, msg) {\n");
    sb.append("  var lbl = document.getElementById(\"messageLbl\");\n");
    sb.append("  if (!lbl) return;\n");
    sb.append("  if (rt == RESPONSE_STATUS_NONE) { lbl.style.display = \"none\"; }\n");
    sb.append("  else if (rt == RESPONSE_STATUS_FAILED) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg error\"; lbl.textContent = msg;\n");
    sb.append("  }\n");
    sb.append("}\n");
    sb.append("</script>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 2. User Registration Page
  // =========================================================================

  /**
   * Renders the user registration page.
   *
   * @param domain              the wave server domain
   * @param message             status message (may be empty)
   * @param responseType        one of "NONE", "FAILED", "SUCCESS"
   * @param disableRegistration if true, show a disabled notice instead of the form
   * @param analyticsAccount    Google Analytics account ID (may be null/empty)
   */
  public static String renderUserRegistrationPage(String domain, String message,
      String responseType, boolean disableRegistration, String analyticsAccount) {
    StringBuilder sb = new StringBuilder(8192);
    sb.append("<!DOCTYPE html>\n<html dir=\"ltr\">\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append("<title>Create Account - SupaWave</title>\n");
    sb.append(AUTH_CSS);
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body onload=\"init()\">\n");

    sb.append(WAVE_SVG);
    sb.append("<div class=\"page-wrapper\">\n");
    sb.append("  <div class=\"brand\">\n");
    sb.append("    ").append(WAVE_LOGO_SVG);
    sb.append("    <div class=\"brand-name\">SupaWave</div>\n");
    sb.append("  </div>\n");

    sb.append("  <div class=\"card\">\n");
    sb.append("    <h1>Create Account</h1>\n");
    sb.append("    <div class=\"subtitle\">Join the wave @").append(escapeHtml(domain)).append("</div>\n");

    sb.append("    <div class=\"msg\" id=\"messageLbl\"></div>\n");
    sb.append("    <span id=\"loginLink\" style=\"display:none;\"> Please <a href=\"/auth/signin\">sign in</a>.</span>\n");

    if (disableRegistration) {
      sb.append("    <p>Registration disabled by administrator.</p>\n");
    } else {
      sb.append("    <form id=\"regForm\" name=\"regForm\" method=\"post\" action=\"\">\n");
      sb.append("      <label for=\"address\">Username</label>\n");
      sb.append("      <div class=\"input-group\">\n");
      sb.append("        <input type=\"text\" name=\"address\" id=\"address\" tabindex=\"1\" autocomplete=\"username\" placeholder=\"your.name\">\n");
      sb.append("        <span class=\"domain-suffix\">@").append(escapeHtml(domain)).append("</span>\n");
      sb.append("      </div>\n");
      sb.append("      <label for=\"password\">Password</label>\n");
      sb.append("      <input type=\"password\" name=\"password\" id=\"password\" tabindex=\"2\" autocomplete=\"new-password\" placeholder=\"Choose a password\">\n");
      sb.append("      <label for=\"verifypass\">Confirm Password</label>\n");
      sb.append("      <input type=\"password\" name=\"verifypass\" id=\"verifypass\" tabindex=\"3\" autocomplete=\"new-password\" placeholder=\"Re-enter your password\">\n");
      sb.append("      <div class=\"buttons\">\n");
      sb.append("        <input type=\"button\" class=\"btn-secondary\" value=\"Cancel\" onclick=\"history.go(-1)\" tabindex=\"4\">\n");
      sb.append("        <input type=\"button\" class=\"btn-primary\" value=\"Create Account\" tabindex=\"5\" onclick=\"validate()\" style=\"flex:1;\">\n");
      sb.append("      </div>\n");
      sb.append("    </form>\n");
    }

    sb.append("    <div class=\"footer-link\">\n");
    sb.append("      Already have an account? <a href=\"/auth/signin\">Sign in</a>\n");
    sb.append("    </div>\n");
    sb.append("  </div>\n"); // .card
    sb.append("</div>\n"); // .page-wrapper

    sb.append("<script>\n");
    sb.append("var RESPONSE_STATUS_NONE = \"NONE\";\n");
    sb.append("var RESPONSE_STATUS_FAILED = \"FAILED\";\n");
    sb.append("var RESPONSE_STATUS_SUCCESS = \"SUCCESS\";\n");
    sb.append("var message = ").append(escapeJsonString(message)).append(";\n");
    sb.append("var responseType = ").append(escapeJsonString(responseType)).append(";\n");
    sb.append("var domain = ").append(escapeJsonString(domain)).append(";\n");
    sb.append("function init() { setFocus(); handleResponse(responseType, message); }\n");
    sb.append("function setFocus() { var el = document.getElementById(\"address\"); if (el) el.focus(); }\n");
    sb.append("function handleResponse(rt, msg) {\n");
    sb.append("  var lbl = document.getElementById(\"messageLbl\");\n");
    sb.append("  if (!lbl) return;\n");
    sb.append("  if (rt == RESPONSE_STATUS_SUCCESS) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg success\"; lbl.textContent = msg;\n");
    sb.append("    document.getElementById(\"loginLink\").style.display = \"inline\";\n");
    sb.append("  } else if (rt == RESPONSE_STATUS_FAILED) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg error\"; lbl.textContent = msg;\n");
    sb.append("  }\n");
    sb.append("}\n");
    sb.append("function validate() {\n");
    sb.append("  var address = document.getElementById(\"address\").value;\n");
    sb.append("  if (address.length < 1) {\n");
    sb.append("    handleResponse(RESPONSE_STATUS_FAILED, \"Username portion of address cannot be empty\"); return;\n");
    sb.append("  }\n");
    sb.append("  if (!isAlphaNumeric(address)) {\n");
    sb.append("    handleResponse(RESPONSE_STATUS_FAILED, \"Only letters (a-z), numbers (0-9), and periods (.) are allowed in Username\"); return;\n");
    sb.append("  }\n");
    sb.append("  var password = document.getElementById(\"password\").value;\n");
    sb.append("  var verifypass = document.getElementById(\"verifypass\").value;\n");
    sb.append("  if (password != null && verifypass != null && password != verifypass) {\n");
    sb.append("    handleResponse(RESPONSE_STATUS_FAILED, \"Password and password verification do not match!\"); return;\n");
    sb.append("  }\n");
    sb.append("  document.getElementById(\"address\").value = address + \"@\" + domain;\n");
    sb.append("  document.getElementById(\"regForm\").submit();\n");
    sb.append("}\n");
    sb.append("function isAlphaNumeric(s) {\n");
    sb.append("  return s.length > 0 && s.search(/[^a-zA-Z0-9.]/g) == -1;\n");
    sb.append("}\n");
    sb.append("</script>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 3. Landing Page (public, for non-authenticated users)
  // =========================================================================

  /**
   * Renders the public landing page shown at / when the user is not logged in.
   *
   * @param domain           the wave server domain
   * @param analyticsAccount Google Analytics account ID (may be null/empty)
   */
  public static String renderLandingPage(String domain, String analyticsAccount) {
    StringBuilder sb = new StringBuilder(16384);
    sb.append("<!DOCTYPE html>\n<html dir=\"ltr\" lang=\"en\">\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append("<title>SupaWave - Real-time Collaborative Communication</title>\n");
    sb.append("<meta name=\"description\" content=\"SupaWave is a real-time collaborative communication platform. Create, share, and collaborate on conversations with rich media and live editing.\">\n");
    sb.append("<style>\n");

    // Reset & base
    sb.append("*, *::before, *::after { box-sizing: border-box; }\n");
    sb.append("body {\n");
    sb.append("  margin: 0; padding: 0;\n");
    sb.append("  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,\n");
    sb.append("    Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', Arial, sans-serif;\n");
    sb.append("  color: #1a1a2e; background: #fff;\n");
    sb.append("  overflow-x: hidden;\n");
    sb.append("}\n");
    sb.append("a { text-decoration: none; }\n");

    // Nav
    sb.append(".nav {\n");
    sb.append("  display: flex; align-items: center; justify-content: space-between;\n");
    sb.append("  padding: 16px 32px; position: relative; z-index: 10;\n");
    sb.append("}\n");
    sb.append(".nav-brand {\n");
    sb.append("  display: flex; align-items: center; gap: 10px;\n");
    sb.append("}\n");
    sb.append(".nav-brand-name {\n");
    sb.append("  font-size: 22px; font-weight: 700; color: ").append(WAVE_PRIMARY).append(";\n");
    sb.append("}\n");
    sb.append(".nav-links { display: flex; gap: 12px; align-items: center; }\n");
    sb.append(".nav-link {\n");
    sb.append("  padding: 8px 20px; font-size: 14px; font-weight: 600;\n");
    sb.append("  border-radius: 8px; transition: all 0.2s;\n");
    sb.append("}\n");
    sb.append(".nav-link-signin {\n");
    sb.append("  color: ").append(WAVE_PRIMARY).append(";\n");
    sb.append("  border: 1.5px solid ").append(WAVE_PRIMARY).append(";\n");
    sb.append("}\n");
    sb.append(".nav-link-signin:hover { background: #f0f8ff; }\n");
    sb.append(".nav-link-register {\n");
    sb.append("  color: #fff; background: ").append(WAVE_PRIMARY).append(";\n");
    sb.append("}\n");
    sb.append(".nav-link-register:hover {\n");
    sb.append("  background: #005f8f;\n");
    sb.append("  box-shadow: 0 4px 12px rgba(0,119,182,0.3);\n");
    sb.append("}\n");

    // Hero
    sb.append(".hero {\n");
    sb.append("  position: relative;\n");
    sb.append("  background: ").append(WAVE_GRADIENT).append(";\n");
    sb.append("  padding: 80px 32px 160px; text-align: center; color: #fff;\n");
    sb.append("  overflow: hidden;\n");
    sb.append("}\n");
    sb.append(".hero-content { position: relative; z-index: 2; max-width: 720px; margin: 0 auto; }\n");
    sb.append(".hero h1 {\n");
    sb.append("  font-size: 52px; font-weight: 800; margin: 0 0 16px;\n");
    sb.append("  letter-spacing: -1px; line-height: 1.1;\n");
    sb.append("}\n");
    sb.append(".hero .tagline {\n");
    sb.append("  font-size: 22px; font-weight: 400; opacity: 0.92;\n");
    sb.append("  margin-bottom: 12px;\n");
    sb.append("}\n");
    sb.append(".hero .description {\n");
    sb.append("  font-size: 16px; opacity: 0.85; max-width: 540px;\n");
    sb.append("  margin: 0 auto 32px; line-height: 1.6;\n");
    sb.append("}\n");
    sb.append(".hero-buttons { display: flex; gap: 16px; justify-content: center; flex-wrap: wrap; }\n");
    sb.append(".hero-btn {\n");
    sb.append("  padding: 14px 36px; font-size: 16px; font-weight: 600;\n");
    sb.append("  border-radius: 10px; transition: all 0.2s; display: inline-block;\n");
    sb.append("}\n");
    sb.append(".hero-btn-primary {\n");
    sb.append("  background: #fff; color: ").append(WAVE_PRIMARY).append(";\n");
    sb.append("}\n");
    sb.append(".hero-btn-primary:hover {\n");
    sb.append("  background: #f0f8ff;\n");
    sb.append("  box-shadow: 0 6px 20px rgba(0,0,0,0.15);\n");
    sb.append("  transform: translateY(-2px);\n");
    sb.append("}\n");
    sb.append(".hero-btn-secondary {\n");
    sb.append("  background: rgba(255,255,255,0.15); color: #fff;\n");
    sb.append("  border: 2px solid rgba(255,255,255,0.4);\n");
    sb.append("  backdrop-filter: blur(4px);\n");
    sb.append("}\n");
    sb.append(".hero-btn-secondary:hover {\n");
    sb.append("  background: rgba(255,255,255,0.25);\n");
    sb.append("  border-color: rgba(255,255,255,0.6);\n");
    sb.append("}\n");

    // Hero wave decoration
    sb.append(".hero-wave {\n");
    sb.append("  position: absolute; bottom: -2px; left: 0; width: 100%; z-index: 1;\n");
    sb.append("  line-height: 0;\n");
    sb.append("}\n");
    sb.append(".hero-wave svg { width: 100%; height: auto; }\n");

    // Features section
    sb.append(".features {\n");
    sb.append("  padding: 80px 32px; max-width: 1000px; margin: 0 auto;\n");
    sb.append("}\n");
    sb.append(".features h2 {\n");
    sb.append("  text-align: center; font-size: 32px; font-weight: 700;\n");
    sb.append("  margin: 0 0 48px; color: #1a1a2e;\n");
    sb.append("}\n");
    sb.append(".features-grid {\n");
    sb.append("  display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));\n");
    sb.append("  gap: 32px;\n");
    sb.append("}\n");
    sb.append(".feature-card {\n");
    sb.append("  background: #f8fbff; border-radius: 12px; padding: 28px;\n");
    sb.append("  border: 1px solid #e8f0fe;\n");
    sb.append("  transition: transform 0.2s, box-shadow 0.2s;\n");
    sb.append("}\n");
    sb.append(".feature-card:hover {\n");
    sb.append("  transform: translateY(-4px);\n");
    sb.append("  box-shadow: 0 8px 24px rgba(0,119,182,0.1);\n");
    sb.append("}\n");
    sb.append(".feature-icon {\n");
    sb.append("  width: 48px; height: 48px; border-radius: 12px;\n");
    sb.append("  background: ").append(WAVE_GRADIENT).append(";\n");
    sb.append("  display: flex; align-items: center; justify-content: center;\n");
    sb.append("  margin-bottom: 16px; font-size: 24px; color: #fff;\n");
    sb.append("}\n");
    sb.append(".feature-card h3 {\n");
    sb.append("  font-size: 18px; font-weight: 600; margin: 0 0 8px;\n");
    sb.append("}\n");
    sb.append(".feature-card p {\n");
    sb.append("  font-size: 14px; color: #555; line-height: 1.6; margin: 0;\n");
    sb.append("}\n");

    // Footer
    sb.append(".landing-footer {\n");
    sb.append("  text-align: center; padding: 32px;\n");
    sb.append("  color: #888; font-size: 13px;\n");
    sb.append("  border-top: 1px solid #eee;\n");
    sb.append("}\n");
    sb.append(".landing-footer a { color: ").append(WAVE_PRIMARY).append("; }\n");

    // Responsive
    sb.append("@media (max-width: 640px) {\n");
    sb.append("  .nav { padding: 12px 16px; }\n");
    sb.append("  .hero { padding: 48px 20px 120px; }\n");
    sb.append("  .hero h1 { font-size: 32px; }\n");
    sb.append("  .hero .tagline { font-size: 18px; }\n");
    sb.append("  .hero .description { font-size: 14px; }\n");
    sb.append("  .features { padding: 48px 20px; }\n");
    sb.append("  .features h2 { font-size: 24px; }\n");
    sb.append("}\n");

    sb.append("</style>\n");
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body>\n");

    // -- Navigation --
    sb.append("<nav class=\"nav\">\n");
    sb.append("  <div class=\"nav-brand\">\n");
    sb.append("    <svg width=\"32\" height=\"32\" viewBox=\"0 0 48 48\" fill=\"none\">\n");
    sb.append("      <circle cx=\"24\" cy=\"24\" r=\"24\" fill=\"").append(WAVE_PRIMARY).append("\"/>\n");
    sb.append("      <path d=\"M10 28 Q16 16 22 28 Q28 40 34 28 Q38 20 38 20\" ");
    sb.append("stroke=\"white\" stroke-width=\"3\" stroke-linecap=\"round\" fill=\"none\"/>\n");
    sb.append("    </svg>\n");
    sb.append("    <span class=\"nav-brand-name\">SupaWave</span>\n");
    sb.append("  </div>\n");
    sb.append("  <div class=\"nav-links\">\n");
    sb.append("    <a href=\"/auth/signin\" class=\"nav-link nav-link-signin\">Sign In</a>\n");
    sb.append("    <a href=\"/auth/register\" class=\"nav-link nav-link-register\">Register</a>\n");
    sb.append("  </div>\n");
    sb.append("</nav>\n");

    // -- Hero --
    sb.append("<section class=\"hero\">\n");
    sb.append("  <div class=\"hero-content\">\n");
    sb.append("    ").append(WAVE_LOGO_SVG.replace("width=\"48\" height=\"48\"", "width=\"72\" height=\"72\""));
    sb.append("    <h1>SupaWave</h1>\n");
    sb.append("    <p class=\"tagline\">Real-time collaborative communication</p>\n");
    sb.append("    <p class=\"description\">Wave brings conversations to life. Create rich, ").append(
        "collaborative discussions where everyone can contribute in real time. ").append(
        "Edit, reply, and build on ideas together &#8212; all in one place.</p>\n");
    sb.append("    <div class=\"hero-buttons\">\n");
    sb.append("      <a href=\"/auth/register\" class=\"hero-btn hero-btn-primary\">Get Started</a>\n");
    sb.append("      <a href=\"/auth/signin\" class=\"hero-btn hero-btn-secondary\">Sign In</a>\n");
    sb.append("    </div>\n");
    sb.append("  </div>\n");
    // Hero bottom wave divider
    sb.append("  <div class=\"hero-wave\">\n");
    sb.append("    <svg viewBox=\"0 0 1440 120\" preserveAspectRatio=\"none\">\n");
    sb.append("      <path d=\"M0,40 C360,120 1080,0 1440,60 L1440,120 L0,120 Z\" fill=\"#ffffff\">\n");
    sb.append("        <animate attributeName=\"d\" dur=\"8s\" repeatCount=\"indefinite\"\n");
    sb.append("          values=\"M0,40 C360,120 1080,0 1440,60 L1440,120 L0,120 Z;\n");
    sb.append("                  M0,70 C360,0 1080,100 1440,30 L1440,120 L0,120 Z;\n");
    sb.append("                  M0,40 C360,120 1080,0 1440,60 L1440,120 L0,120 Z\"/>\n");
    sb.append("      </path>\n");
    sb.append("    </svg>\n");
    sb.append("  </div>\n");
    sb.append("</section>\n");

    // -- Features --
    sb.append("<section class=\"features\">\n");
    sb.append("  <h2>Why SupaWave?</h2>\n");
    sb.append("  <div class=\"features-grid\">\n");

    sb.append("    <div class=\"feature-card\">\n");
    sb.append("      <div class=\"feature-icon\">\n");
    sb.append("        <svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"white\" stroke-width=\"2\" stroke-linecap=\"round\">\n");
    sb.append("          <path d=\"M13 2L3 14h9l-1 8 10-12h-9l1-8z\"/>\n");
    sb.append("        </svg>\n");
    sb.append("      </div>\n");
    sb.append("      <h3>Real-Time Collaboration</h3>\n");
    sb.append("      <p>See changes as they happen. Multiple participants can edit and contribute simultaneously with character-by-character live updates.</p>\n");
    sb.append("    </div>\n");

    sb.append("    <div class=\"feature-card\">\n");
    sb.append("      <div class=\"feature-icon\">\n");
    sb.append("        <svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"white\" stroke-width=\"2\" stroke-linecap=\"round\">\n");
    sb.append("          <path d=\"M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z\"/>\n");
    sb.append("        </svg>\n");
    sb.append("      </div>\n");
    sb.append("      <h3>Threaded Conversations</h3>\n");
    sb.append("      <p>Organize discussions naturally. Reply inline, branch conversations, and keep context intact across complex collaborative threads.</p>\n");
    sb.append("    </div>\n");

    sb.append("    <div class=\"feature-card\">\n");
    sb.append("      <div class=\"feature-icon\">\n");
    sb.append("        <svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"white\" stroke-width=\"2\" stroke-linecap=\"round\">\n");
    sb.append("          <circle cx=\"12\" cy=\"12\" r=\"10\"/>\n");
    sb.append("          <path d=\"M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z\"/>\n");
    sb.append("        </svg>\n");
    sb.append("      </div>\n");
    sb.append("      <h3>Open &amp; Federated</h3>\n");
    sb.append("      <p>Built on the open Apache Wave protocol. Self-host your own server and communicate across federated Wave instances.</p>\n");
    sb.append("    </div>\n");

    sb.append("  </div>\n");
    sb.append("</section>\n");

    // -- Footer --
    sb.append("<footer class=\"landing-footer\">\n");
    sb.append("  Powered by <a href=\"https://incubator.apache.org/projects/wave.html\">Apache Wave</a>\n");
    sb.append("  &middot; @").append(escapeHtml(domain)).append("\n");
    sb.append("</footer>\n");

    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 4. Wave Client Page
  // =========================================================================

  /**
   * Renders the main wave client (GWT host) page.
   *
   * @param sessionJson      session object (domain, address, id_seed)
   * @param clientFlags      client flag overrides
   * @param websocketAddress the websocket host:port for the client to connect to
   * @param topBarHtml       pre-rendered top-bar HTML fragment
   * @param analyticsAccount Google Analytics account ID (may be null/empty)
   */
  public static String renderWaveClientPage(JSONObject sessionJson, JSONObject clientFlags,
      String websocketAddress, String topBarHtml, String analyticsAccount) {
    StringBuilder sb = new StringBuilder(4096);
    sb.append("<!DOCTYPE html>\n<html>\n<head>\n");
    sb.append("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
    sb.append("<title>SupaWave</title>\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    // Session variables
    sb.append("<script type=\"text/javascript\">\n");
    sb.append("var __session = ").append(sessionJson.toString()).append(";\n");
    sb.append("var __websocket_address = ").append(escapeJsonString(websocketAddress)).append(";\n");
    sb.append("var __client_flags = ").append(clientFlags.toString()).append(";\n");
    sb.append("</script>\n");
    // Inline styles for wave client top bar
    sb.append("<style type=\"text/css\">\n");
    sb.append("body { margin: 0; }\n");
    sb.append(".topbar {\n");
    sb.append("  height: 40px; line-height: 40px;\n");
    sb.append("  background: #fff;\n");
    sb.append("  border-bottom: 1px solid #e2e8f0;\n");
    sb.append("  box-shadow: 0 1px 3px rgba(0,0,0,0.06);\n");
    sb.append("  overflow: visible;\n");
    sb.append("  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,\n");
    sb.append("    Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', Arial, sans-serif;\n");
    sb.append("  font-size: 14px; padding: 0 12px;\n");
    sb.append("  position: relative; z-index: 1;\n");
    sb.append("  display: flex; align-items: center;\n");
    sb.append("}\n");
    sb.append(".topbar-brand { display: flex; align-items: center; text-decoration: none; gap: 8px; }\n");
    sb.append(".topbar-brand svg { flex-shrink: 0; }\n");
    sb.append(".title {\n");
    sb.append("  font-size: 17px; font-weight: 700; color: ").append(WAVE_PRIMARY).append(";\n");
    sb.append("  letter-spacing: -0.3px;\n");
    sb.append("}\n");
    sb.append(".banner { margin-left: 12px; }\n");
    sb.append(".lang { height: 19px; }\n");
    sb.append(".domain { color: #8896a6; font-weight: 400; }\n");
    sb.append(".info { margin-left: auto; display: flex; align-items: center; gap: 8px; font-size: 13px; color: #4a5568; }\n");
    sb.append(".info a { color: ").append(WAVE_PRIMARY).append("; text-decoration: none; font-weight: 500; }\n");
    sb.append(".info a:hover { text-decoration: underline; }\n");
    sb.append(".online { color: #38a169; }\n");
    sb.append(".connecting { color: #dd6b20; font-weight: 600; }\n");
    sb.append(".offline { color: #e53e3e; font-weight: 600; }\n");
    sb.append(".user-menu { position: relative; display: inline-block; cursor: pointer; }\n");
    sb.append(".user-menu-toggle { background: none; border: none; color: #4a5568; cursor: pointer; font: inherit; padding: 4px 10px; border-radius: 6px; transition: background 0.15s; }\n");
    sb.append(".user-menu-toggle:hover { background: #f0f4f8; }\n");
    sb.append(".user-menu-dropdown { display: none; position: absolute; right: 0; top: 100%; background: #fff; border-radius: 8px; box-shadow: 0 4px 20px rgba(0,0,0,0.12); min-width: 210px; z-index: 1000; padding: 4px 0; margin-top: 6px; border: 1px solid #e2e8f0; }\n");
    sb.append(".user-menu-dropdown.open { display: block; }\n");
    sb.append(".user-menu-dropdown a { display: block; padding: 8px 16px; color: #333; text-decoration: none; font-size: 13px; transition: background 0.1s; }\n");
    sb.append(".user-menu-dropdown a:hover { background: #f0f4f8; color: ").append(WAVE_PRIMARY).append("; }\n");
    sb.append(".user-menu-dropdown .divider { border-top: 1px solid #e2e8f0; margin: 4px 0; }\n");
    // Wave panel theme overrides (ocean blue/teal for GWT panels)
    sb.append(WAVE_PANEL_CSS);
    sb.append("</style>\n");
    // GWT stats + nocache JS
    sb.append("<script type=\"text/javascript\">\n");
    sb.append("var stats = window.__stats = [];\n");
    sb.append("window.__gwtStatsEvent = function(evt) {\n");
    sb.append("  stats[stats.length] = evt;\n");
    sb.append("  var listener = window.__stats_listener;\n");
    sb.append("  listener && listener(evt);\n");
    sb.append("  return true;\n");
    sb.append("}\n");
    sb.append("</script>\n");
    sb.append("<script type=\"text/javascript\" src=\"webclient/webclient.nocache.js\"></script>\n");
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body>\n");
    // GWT history frame
    sb.append("<iframe src=\"javascript:''\" id=\"__gwt_historyFrame\" ");
    sb.append("style=\"position:absolute;width:0;height:0;border:0\"></iframe>\n");
    // Top bar
    sb.append(topBarHtml).append("\n");
    // App container
    sb.append("<div id=\"app\" style=\"position:absolute; top:41px; right:0px; bottom:0px; left:0px;\"></div>\n");
    sb.append("<noscript>\n");
    sb.append("<div style=\"width:22em;position:absolute;left:50%;margin-left:-11em;");
    sb.append("color:red;background-color:white;border:1px solid red;padding:4px;font-family:sans-serif\">\n");
    sb.append("Your web browser must have JavaScript enabled in order for this application to display correctly.\n");
    sb.append("</div>\n");
    sb.append("</noscript>\n");
    sb.append("<script>\n");
    sb.append("(function() {\n");
    sb.append("  var toggle = document.querySelector('.user-menu-toggle');\n");
    sb.append("  if (toggle) {\n");
    sb.append("    toggle.addEventListener('click', function(e) {\n");
    sb.append("      e.stopPropagation();\n");
    sb.append("      document.querySelector('.user-menu-dropdown').classList.toggle('open');\n");
    sb.append("    });\n");
    sb.append("  }\n");
    sb.append("  document.addEventListener('click', function() {\n");
    sb.append("    var d = document.querySelector('.user-menu-dropdown');\n");
    sb.append("    if (d) d.classList.remove('open');\n");
    sb.append("  });\n");
    sb.append("  window.openVersionHistory = function() {\n");
    sb.append("    var hash = window.location.hash;\n");
    sb.append("    if (!hash || hash.length < 2) { alert('No wave is currently open.'); return; }\n");
    sb.append("    // Hash format: #waveDomain/waveId  (e.g. #example.com/w+abc123)\n");
    sb.append("    var ref = hash.substring(1);\n");
    sb.append("    var parts = ref.split('/');\n");
    sb.append("    if (parts.length < 2) { alert('Cannot determine wave ID from URL.'); return; }\n");
    sb.append("    var waveDomain = parts[0];\n");
    sb.append("    var waveId = parts[1];\n");
    sb.append("    // Default to conv+root wavelet in the wave's domain\n");
    sb.append("    var url = '/history/' + encodeURIComponent(waveDomain) + '/' + encodeURIComponent(waveId) + '/' + encodeURIComponent(waveDomain) + '/conv+root';\n");
    sb.append("    window.open(url, '_blank');\n");
    sb.append("  };\n");
    sb.append("})();\n");
    sb.append("</script>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 4. Top Bar Fragment
  // =========================================================================

  /**
   * Renders the top-bar HTML fragment shown above the wave client.
   *
   * @param username user part of the address (before @), or null if not logged in
   * @param domain   the wave server domain
   */
  public static String renderTopBar(String username, String domain) {
    StringBuilder sb = new StringBuilder(2048);
    sb.append("<div class=\"topbar\">\n");
    sb.append("  <a href=\"/\" class=\"topbar-brand\">").append(WAVE_LOGO_SVG_SMALL);
    sb.append("<span class=\"title\">SupaWave</span></a>\n");
    sb.append("  <div class=\"banner\" id=\"banner\"></div>\n");
    sb.append("  <div class=\"info\">\n");
    if (username == null) {
      sb.append("    <a href=\"/auth/register\">Register</a>\n");
      sb.append("    <a href=\"/auth/signin?r=/\">Sign In</a>\n");
    } else {
      sb.append("    <select id=\"lang\" class=\"lang\" size=\"1\"></select>\n");
      sb.append("    <span id=\"unsavedStateContainer\" style=\"width:60px\">Saved</span>\n");
      sb.append("    <span id=\"netstatus\" class=\"offline\">Offline</span>\n");
      sb.append("    <div class=\"user-menu\">\n");
      sb.append("      <button class=\"user-menu-toggle\">\n");
      sb.append("        ").append(escapeHtml(username));
      sb.append("<span class=\"domain\">@").append(escapeHtml(domain)).append("</span>");
      sb.append(" &#9662;\n");
      sb.append("      </button>\n");
      sb.append("      <div class=\"user-menu-dropdown\">\n");
      sb.append("        <a href=\"/robot/register/create\">Robot Registration</a>\n");
      sb.append("        <a href=\"/robot/dataapi/token\">API Token</a>\n");
      sb.append("        <a href=\"#\" onclick=\"window.openVersionHistory(); return false;\">Version History</a>\n");
      sb.append("        <div class=\"divider\"></div>\n");
      sb.append("        <a id=\"signout\" href=\"/auth/signout?r=/\">Sign Out</a>\n");
      sb.append("      </div>\n");
      sb.append("    </div>\n");
    }
    sb.append("  </div>\n");
    sb.append("</div>");
    return sb.toString();
  }

  // =========================================================================
  // 5. Robot Registration Page
  // =========================================================================

  /**
   * Renders the robot registration form page.
   *
   * @param domain           the wave server domain
   * @param message          status/error message (may be empty)
   * @param analyticsAccount Google Analytics account ID (may be null/empty)
   */
  public static String renderRobotRegistrationPage(String domain, String message,
      String analyticsAccount) {
    StringBuilder sb = new StringBuilder(2048);
    sb.append("<!DOCTYPE html>\n<html>\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<title>Robot Registration</title>\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append(AUTH_CSS);
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body>\n");
    sb.append(WAVE_SVG);
    sb.append("<div class=\"page-wrapper\">\n");
    sb.append("  <div class=\"brand\">\n");
    sb.append("    ").append(WAVE_LOGO_SVG);
    sb.append("    <div class=\"brand-name\">SupaWave</div>\n");
    sb.append("  </div>\n");
    sb.append("  <div class=\"card\">\n");
    sb.append("    <h1>Robot Registration</h1>\n");
    if (message != null && !message.isEmpty()) {
      sb.append("    <p><b>").append(escapeHtml(message)).append("</b></p>\n");
    }
    sb.append("    <form method=\"post\" action=\"\">\n");
    sb.append("      <label for=\"username\">Robot Username</label>\n");
    sb.append("      <div class=\"input-group\">\n");
    sb.append("        <input type=\"text\" name=\"username\" id=\"username\">\n");
    sb.append("        <span class=\"domain-suffix\">@").append(escapeHtml(domain)).append("</span>\n");
    sb.append("      </div>\n");
    sb.append("      <label for=\"location\">Robot URL</label>\n");
    sb.append("      <input type=\"text\" name=\"location\" id=\"location\">\n");
    sb.append("      <label for=\"token_expiry\">Token Expiry</label>\n");
    sb.append("      <select name=\"token_expiry\" id=\"token_expiry\" style=\"width:100%;padding:10px 12px;font-size:14px;border:1.5px solid #d0d5dd;border-radius:8px;margin-bottom:14px;background:#fafbfc;\">\n");
    sb.append("        <option value=\"0\" selected>No expiry</option>\n");
    sb.append("        <option value=\"3600\">1 hour</option>\n");
    sb.append("        <option value=\"86400\">1 day</option>\n");
    sb.append("        <option value=\"604800\">1 week</option>\n");
    sb.append("      </select>\n");
    sb.append("      <input type=\"submit\" class=\"btn-primary\" value=\"Register\" style=\"width:100%;\">\n");
    sb.append("    </form>\n");
    sb.append("    <div class=\"footer-link\">\n");
    sb.append("      <a href=\"/\">&larr; Back to SupaWave</a>\n");
    sb.append("    </div>\n");
    sb.append("  </div>\n"); // .card
    sb.append("</div>\n"); // .page-wrapper
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 6. Robot Registration Success Page
  // =========================================================================

  /**
   * Renders the page shown after successful robot registration.
   *
   * @param token            the consumer token (robot address)
   * @param tokenSecret      the consumer token secret
   * @param analyticsAccount Google Analytics account ID (may be null/empty)
   */
  public static String renderRobotRegistrationSuccessPage(String token, String tokenSecret,
      String analyticsAccount) {
    StringBuilder sb = new StringBuilder(2048);
    sb.append("<!DOCTYPE html>\n<html>\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<title>Robot Successfully Registered</title>\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append(AUTH_CSS);
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body>\n");
    sb.append(WAVE_SVG);
    sb.append("<div class=\"page-wrapper\">\n");
    sb.append("  <div class=\"brand\">\n");
    sb.append("    ").append(WAVE_LOGO_SVG);
    sb.append("    <div class=\"brand-name\">SupaWave</div>\n");
    sb.append("  </div>\n");
    sb.append("  <div class=\"card\">\n");
    sb.append("    <h1>Robot Registered</h1>\n");
    sb.append("    <p>Your robot has been successfully registered. Please take note of the consumer\n");
    sb.append("    token and token secret to use for the Active API.</p>\n");
    sb.append("    <table>\n");
    sb.append("      <tr><td><b>Consumer Token</b></td><td>").append(escapeHtml(token)).append("</td></tr>\n");
    sb.append("      <tr><td><b>Consumer Token Secret</b></td><td>").append(escapeHtml(tokenSecret)).append("</td></tr>\n");
    sb.append("    </table>\n");
    sb.append("    <div class=\"footer-link\">\n");
    sb.append("      <a href=\"/\">&larr; Back to SupaWave</a>\n");
    sb.append("    </div>\n");
    sb.append("  </div>\n"); // .card
    sb.append("</div>\n"); // .page-wrapper
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 7. OAuth Authorize Token Page
  // =========================================================================

  /**
   * Renders the OAuth token authorization page.
   *
   * @param user      the logged-in user address
   * @param xsrfToken XSRF protection token
   */
  public static String renderOAuthAuthorizeTokenPage(String user, String xsrfToken) {
    StringBuilder sb = new StringBuilder(2048);
    sb.append("<!DOCTYPE html>\n<html>\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<title>Authorization Required</title>\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append(AUTH_CSS);
    sb.append("</head>\n<body>\n");
    sb.append(WAVE_SVG);
    sb.append("<div class=\"page-wrapper\">\n");
    sb.append("  <div class=\"brand\">\n");
    sb.append("    ").append(WAVE_LOGO_SVG);
    sb.append("    <div class=\"brand-name\">SupaWave</div>\n");
    sb.append("  </div>\n");
    sb.append("  <div class=\"card\">\n");
    sb.append("    <h1>Authorization Required</h1>\n");
    sb.append("    <p>You are logged in as <b>").append(escapeHtml(user)).append("</b>.</p>\n");
    sb.append("    <p>A program would like to access your waves and perform operations on your behalf.</p>\n");
    sb.append("    <form method=\"post\" action=\"\">\n");
    sb.append("      <input type=\"hidden\" name=\"token\" value=\"").append(escapeHtml(xsrfToken)).append("\">\n");
    sb.append("      <div class=\"buttons\">\n");
    sb.append("        <input type=\"submit\" class=\"btn-primary\" value=\"Agree\" name=\"agree\">\n");
    sb.append("        <input type=\"submit\" class=\"btn-secondary\" value=\"Cancel\" name=\"cancel\">\n");
    sb.append("      </div>\n");
    sb.append("    </form>\n");
    sb.append("  </div>\n"); // .card
    sb.append("</div>\n"); // .page-wrapper
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 8. OAuth Authorization Code Page
  // =========================================================================

  /**
   * Renders the page that displays an OAuth authorization code.
   *
   * @param code the authorization code to show
   */
  public static String renderOAuthAuthorizationCodePage(String code) {
    StringBuilder sb = new StringBuilder(1024);
    sb.append("<!DOCTYPE html>\n<html>\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<title>Authorization code</title>\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append(AUTH_CSS);
    sb.append("</head>\n<body>\n");
    sb.append(WAVE_SVG);
    sb.append("<div class=\"page-wrapper\">\n");
    sb.append("  <div class=\"brand\">\n");
    sb.append("    ").append(WAVE_LOGO_SVG);
    sb.append("    <div class=\"brand-name\">SupaWave</div>\n");
    sb.append("  </div>\n");
    sb.append("  <div class=\"card\">\n");
    sb.append("    <h1>Authorization Code</h1>\n");
    sb.append("    <p>Please copy this code, switch to your application and paste it there:</p>\n");
    sb.append("    <input id=\"code\" type=\"text\" readonly ");
    sb.append("style=\"width:100%;font-family:monospace;\" ");
    sb.append("onclick=\"this.focus();this.select();\" ");
    sb.append("value=\"").append(escapeHtml(code)).append("\">\n");
    sb.append("  </div>\n"); // .card
    sb.append("</div>\n"); // .page-wrapper
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 9. Password Reset Request Page
  // =========================================================================

  /**
   * Renders the password reset request page (enter your username/email).
   */
  public static String renderPasswordResetRequestPage(String domain, String message,
      String responseType, String analyticsAccount) {
    StringBuilder sb = new StringBuilder(4096);
    sb.append("<!DOCTYPE html>\n<html dir=\"ltr\">\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append("<title>Reset Password - SupaWave</title>\n");
    sb.append(AUTH_CSS);
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body onload=\"init()\">\n");

    sb.append(WAVE_SVG);
    sb.append("<div class=\"page-wrapper\">\n");
    sb.append("  <div class=\"brand\">\n");
    sb.append("    ").append(WAVE_LOGO_SVG);
    sb.append("    <div class=\"brand-name\">SupaWave</div>\n");
    sb.append("  </div>\n");

    sb.append("  <div class=\"card\">\n");
    sb.append("    <h1>Reset Password</h1>\n");
    sb.append("    <div class=\"subtitle\">Enter your username to receive a reset link</div>\n");

    sb.append("    <div class=\"msg\" id=\"messageLbl\"></div>\n");

    sb.append("    <form id=\"resetForm\" method=\"post\" action=\"\">\n");
    sb.append("      <label for=\"address\">Username</label>\n");
    sb.append("      <div class=\"input-group\">\n");
    sb.append("        <input type=\"text\" name=\"address\" id=\"address\" autocomplete=\"username\">\n");
    sb.append("        <span class=\"domain-suffix\">@").append(escapeHtml(domain)).append("</span>\n");
    sb.append("      </div>\n");
    sb.append("      <input type=\"submit\" class=\"btn-primary\" value=\"Send Reset Link\" style=\"width:100%;\">\n");
    sb.append("    </form>\n");

    sb.append("    <div class=\"footer-link\">\n");
    sb.append("      <a href=\"/auth/signin\">&larr; Back to Sign In</a>\n");
    sb.append("    </div>\n");
    sb.append("  </div>\n"); // .card
    sb.append("</div>\n"); // .page-wrapper

    sb.append("<script>\n");
    sb.append("var RESPONSE_STATUS_NONE = \"NONE\";\n");
    sb.append("var RESPONSE_STATUS_FAILED = \"FAILED\";\n");
    sb.append("var RESPONSE_STATUS_SUCCESS = \"SUCCESS\";\n");
    sb.append("var message = ").append(escapeJsonString(message)).append(";\n");
    sb.append("var responseType = ").append(escapeJsonString(responseType)).append(";\n");
    sb.append("function init() { handleResponse(responseType, message); }\n");
    sb.append("function handleResponse(rt, msg) {\n");
    sb.append("  var lbl = document.getElementById(\"messageLbl\");\n");
    sb.append("  if (!lbl) return;\n");
    sb.append("  if (rt == RESPONSE_STATUS_NONE) { lbl.style.display = \"none\"; }\n");
    sb.append("  else if (rt == RESPONSE_STATUS_FAILED) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg error\"; lbl.innerHTML = msg;\n");
    sb.append("  } else if (rt == RESPONSE_STATUS_SUCCESS) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg success\"; lbl.innerHTML = msg;\n");
    sb.append("  }\n");
    sb.append("}\n");
    sb.append("</script>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 10. Password Reset Form Page (new password)
  // =========================================================================

  /**
   * Renders the password reset form page (enter new password).
   */
  public static String renderPasswordResetFormPage(String domain, String token, String message,
      String responseType, String analyticsAccount) {
    StringBuilder sb = new StringBuilder(4096);
    sb.append("<!DOCTYPE html>\n<html dir=\"ltr\">\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append("<title>Set New Password - SupaWave</title>\n");
    sb.append(AUTH_CSS);
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body onload=\"init()\">\n");

    sb.append(WAVE_SVG);
    sb.append("<div class=\"page-wrapper\">\n");
    sb.append("  <div class=\"brand\">\n");
    sb.append("    ").append(WAVE_LOGO_SVG);
    sb.append("    <div class=\"brand-name\">SupaWave</div>\n");
    sb.append("  </div>\n");

    sb.append("  <div class=\"card\">\n");
    sb.append("    <h1>Set New Password</h1>\n");
    sb.append("    <div class=\"subtitle\">Enter your new password below</div>\n");

    sb.append("    <div class=\"msg\" id=\"messageLbl\"></div>\n");

    sb.append("    <form id=\"resetForm\" method=\"post\" action=\"\">\n");
    sb.append("      <input type=\"hidden\" name=\"token\" value=\"").append(escapeHtml(token)).append("\">\n");
    sb.append("      <label for=\"password\">New Password</label>\n");
    sb.append("      <input type=\"password\" name=\"password\" id=\"password\" autocomplete=\"new-password\">\n");
    sb.append("      <label for=\"confirmPassword\">Confirm Password</label>\n");
    sb.append("      <input type=\"password\" name=\"confirmPassword\" id=\"confirmPassword\" autocomplete=\"new-password\">\n");
    sb.append("      <input type=\"submit\" class=\"btn-primary\" value=\"Update Password\" style=\"width:100%;\">\n");
    sb.append("    </form>\n");

    sb.append("    <div class=\"footer-link\">\n");
    sb.append("      <a href=\"/auth/signin\">&larr; Back to Sign In</a>\n");
    sb.append("    </div>\n");
    sb.append("  </div>\n"); // .card
    sb.append("</div>\n"); // .page-wrapper

    sb.append("<script>\n");
    sb.append("var RESPONSE_STATUS_NONE = \"NONE\";\n");
    sb.append("var RESPONSE_STATUS_FAILED = \"FAILED\";\n");
    sb.append("var RESPONSE_STATUS_SUCCESS = \"SUCCESS\";\n");
    sb.append("var message = ").append(escapeJsonString(message)).append(";\n");
    sb.append("var responseType = ").append(escapeJsonString(responseType)).append(";\n");
    sb.append("function init() { handleResponse(responseType, message); }\n");
    sb.append("function handleResponse(rt, msg) {\n");
    sb.append("  var lbl = document.getElementById(\"messageLbl\");\n");
    sb.append("  if (!lbl) return;\n");
    sb.append("  if (rt == RESPONSE_STATUS_NONE) { lbl.style.display = \"none\"; }\n");
    sb.append("  else if (rt == RESPONSE_STATUS_FAILED) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg error\"; lbl.innerHTML = msg;\n");
    sb.append("  } else if (rt == RESPONSE_STATUS_SUCCESS) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg success\"; lbl.innerHTML = msg;\n");
    sb.append("  }\n");
    sb.append("}\n");
    sb.append("</script>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 11. Magic Link Request Page
  // =========================================================================

  /**
   * Renders the magic link login request page.
   */
  public static String renderMagicLinkRequestPage(String domain, String message,
      String responseType, String analyticsAccount) {
    StringBuilder sb = new StringBuilder(4096);
    sb.append("<!DOCTYPE html>\n<html dir=\"ltr\">\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append("<title>Login with Email - SupaWave</title>\n");
    sb.append(AUTH_CSS);
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body onload=\"init()\">\n");

    sb.append(WAVE_SVG);
    sb.append("<div class=\"page-wrapper\">\n");
    sb.append("  <div class=\"brand\">\n");
    sb.append("    ").append(WAVE_LOGO_SVG);
    sb.append("    <div class=\"brand-name\">SupaWave</div>\n");
    sb.append("  </div>\n");

    sb.append("  <div class=\"card\">\n");
    sb.append("    <h1>Login with Email</h1>\n");
    sb.append("    <div class=\"subtitle\">Enter your username to receive a login link</div>\n");

    sb.append("    <div class=\"msg\" id=\"messageLbl\"></div>\n");

    sb.append("    <form id=\"magicForm\" method=\"post\" action=\"\">\n");
    sb.append("      <label for=\"address\">Username</label>\n");
    sb.append("      <div class=\"input-group\">\n");
    sb.append("        <input type=\"text\" name=\"address\" id=\"address\" autocomplete=\"username\">\n");
    sb.append("        <span class=\"domain-suffix\">@").append(escapeHtml(domain)).append("</span>\n");
    sb.append("      </div>\n");
    sb.append("      <input type=\"submit\" class=\"btn-primary\" value=\"Send Login Link\" style=\"width:100%;\">\n");
    sb.append("    </form>\n");

    sb.append("    <div class=\"footer-link\">\n");
    sb.append("      <a href=\"/auth/signin\">&larr; Back to Sign In</a>\n");
    sb.append("    </div>\n");
    sb.append("  </div>\n"); // .card
    sb.append("</div>\n"); // .page-wrapper

    sb.append("<script>\n");
    sb.append("var RESPONSE_STATUS_NONE = \"NONE\";\n");
    sb.append("var RESPONSE_STATUS_FAILED = \"FAILED\";\n");
    sb.append("var RESPONSE_STATUS_SUCCESS = \"SUCCESS\";\n");
    sb.append("var message = ").append(escapeJsonString(message)).append(";\n");
    sb.append("var responseType = ").append(escapeJsonString(responseType)).append(";\n");
    sb.append("function init() { handleResponse(responseType, message); }\n");
    sb.append("function handleResponse(rt, msg) {\n");
    sb.append("  var lbl = document.getElementById(\"messageLbl\");\n");
    sb.append("  if (!lbl) return;\n");
    sb.append("  if (rt == RESPONSE_STATUS_NONE) { lbl.style.display = \"none\"; }\n");
    sb.append("  else if (rt == RESPONSE_STATUS_FAILED) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg error\"; lbl.innerHTML = msg;\n");
    sb.append("  } else if (rt == RESPONSE_STATUS_SUCCESS) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg success\"; lbl.innerHTML = msg;\n");
    sb.append("  }\n");
    sb.append("}\n");
    sb.append("</script>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 12. Email Confirmation Page
  // =========================================================================

  /**
   * Renders the email confirmation result page.
   */
  public static String renderEmailConfirmationPage(String domain, String message,
      String responseType, String analyticsAccount) {
    StringBuilder sb = new StringBuilder(4096);
    sb.append("<!DOCTYPE html>\n<html dir=\"ltr\">\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append("<title>Email Confirmation - SupaWave</title>\n");
    sb.append(AUTH_CSS);
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body onload=\"init()\">\n");

    sb.append(WAVE_SVG);
    sb.append("<div class=\"page-wrapper\">\n");
    sb.append("  <div class=\"brand\">\n");
    sb.append("    ").append(WAVE_LOGO_SVG);
    sb.append("    <div class=\"brand-name\">SupaWave</div>\n");
    sb.append("  </div>\n");

    sb.append("  <div class=\"card\">\n");
    sb.append("    <h1>Email Confirmation</h1>\n");

    sb.append("    <div class=\"msg\" id=\"messageLbl\"></div>\n");

    sb.append("    <div class=\"footer-link\">\n");
    sb.append("      <a href=\"/auth/signin\">Go to Sign In</a>\n");
    sb.append("    </div>\n");
    sb.append("  </div>\n"); // .card
    sb.append("</div>\n"); // .page-wrapper

    sb.append("<script>\n");
    sb.append("var RESPONSE_STATUS_NONE = \"NONE\";\n");
    sb.append("var RESPONSE_STATUS_FAILED = \"FAILED\";\n");
    sb.append("var RESPONSE_STATUS_SUCCESS = \"SUCCESS\";\n");
    sb.append("var message = ").append(escapeJsonString(message)).append(";\n");
    sb.append("var responseType = ").append(escapeJsonString(responseType)).append(";\n");
    sb.append("function init() { handleResponse(responseType, message); }\n");
    sb.append("function handleResponse(rt, msg) {\n");
    sb.append("  var lbl = document.getElementById(\"messageLbl\");\n");
    sb.append("  if (!lbl) return;\n");
    sb.append("  if (rt == RESPONSE_STATUS_NONE) { lbl.style.display = \"none\"; }\n");
    sb.append("  else if (rt == RESPONSE_STATUS_FAILED) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg error\"; lbl.innerHTML = msg;\n");
    sb.append("  } else if (rt == RESPONSE_STATUS_SUCCESS) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg success\"; lbl.innerHTML = msg;\n");
    sb.append("  }\n");
    sb.append("}\n");
    sb.append("</script>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 13. Analytics Fragment (private helper)
  // =========================================================================

  /**
   * Appends the Google Analytics tracking script if an account is configured.
   *
   * @param sb      the builder to append to
   * @param account the GA account ID (may be null or empty)
   * @param error   optional custom-variable error string (may be null)
   */
  private static void appendAnalyticsFragment(StringBuilder sb, String account, String error) {
    if (account == null || account.isEmpty()) {
      return;
    }
    sb.append("<script type=\"text/javascript\">\n");
    sb.append("var _gaq = _gaq || [];\n");
    sb.append("_gaq.push(['_setAccount', ").append(escapeJsonString(account)).append("]);\n");
    if (error != null && !error.isEmpty()) {
      sb.append("_gaq.push(['_setCustomVar', 1, 'error', ").append(escapeJsonString(error)).append(", 3]);\n");
    }
    sb.append("_gaq.push(['_trackPageview']);\n");
    sb.append("(function() {\n");
    sb.append("  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\n");
    sb.append("  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n");
    sb.append("  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\n");
    sb.append("})();\n");
    sb.append("</script>\n");
  }

  // =========================================================================
  // HTML / JSON escaping helpers
  // =========================================================================

  /**
   * Escapes a string for safe inclusion in HTML content or attribute values.
   * Handles the five XML special characters: {@code & < > " '}.
   *
   * @param s the raw string (may be null)
   * @return the escaped string, or empty string if null
   */
  public static String escapeHtml(String s) {
    if (s == null) return "";
    StringBuilder sb = new StringBuilder(s.length() + 16);
    for (int i = 0; i < s.length(); i++) {
      char c = s.charAt(i);
      switch (c) {
        case '&':  sb.append("&amp;");  break;
        case '<':  sb.append("&lt;");   break;
        case '>':  sb.append("&gt;");   break;
        case '"':  sb.append("&quot;"); break;
        case '\'': sb.append("&#39;");  break;
        default:   sb.append(c);
      }
    }
    return sb.toString();
  }

  /**
   * Wraps a string as a JSON string literal (with surrounding quotes), escaping
   * special characters. Returns {@code "null"} (unquoted) for null input.
   *
   * @param s the raw string (may be null)
   * @return a JSON string literal, e.g. {@code "hello \"world\""}
   */
  public static String escapeJsonString(String s) {
    if (s == null) return "null";
    StringBuilder sb = new StringBuilder(s.length() + 16);
    sb.append('"');
    for (int i = 0; i < s.length(); i++) {
      char c = s.charAt(i);
      switch (c) {
        case '"':  sb.append("\\\""); break;
        case '\\': sb.append("\\\\"); break;
        case '\n': sb.append("\\n");  break;
        case '\r': sb.append("\\r");  break;
        case '\t': sb.append("\\t");  break;
        case '/':  sb.append("\\/");  break;
        default:
          if (c < 0x20) {
            sb.append(String.format("\\u%04x", (int) c));
          } else {
            sb.append(c);
          }
      }
    }
    sb.append('"');
    return sb.toString();
  }
}
