/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.waveprotocol.box.server.rpc;

import org.json.JSONObject;

/**
 * Pure-Java replacement for the 9 GXP templates formerly generated by
 * {@code com.google.gxp}. Each public static method returns a complete HTML
 * page (or fragment) as a {@link String}.
 *
 * <p>Auth/registration pages use a modern centered-card CSS layout. The wave
 * client page preserves the original structure required by the GWT webclient.
 */
public final class HtmlRenderer {

  private HtmlRenderer() {} // utility class

  // =========================================================================
  // Shared CSS for auth-style pages (login, registration, robot registration)
  // =========================================================================

  private static final String AUTH_CSS =
      "<style>\n"
      + "*, *::before, *::after { box-sizing: border-box; }\n"
      + "body {\n"
      + "  margin: 0; padding: 0;\n"
      + "  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,\n"
      + "    Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', Arial, sans-serif;\n"
      + "  background: #f0f2f5;\n"
      + "  color: #333;\n"
      + "}\n"
      + ".card {\n"
      + "  max-width: 420px; margin: 60px auto; padding: 32px 28px;\n"
      + "  background: #fff;\n"
      + "  border-radius: 8px;\n"
      + "  box-shadow: 0 2px 8px rgba(0,0,0,0.10);\n"
      + "}\n"
      + ".card h1 {\n"
      + "  font-size: 22px; margin: 0 0 6px; font-weight: 600;\n"
      + "}\n"
      + ".card .subtitle {\n"
      + "  font-size: 14px; color: #666; margin-bottom: 20px;\n"
      + "}\n"
      + "label { display: block; font-size: 14px; font-weight: 500; margin-bottom: 4px; }\n"
      + ".input-group {\n"
      + "  display: flex; align-items: center; margin-bottom: 14px;\n"
      + "}\n"
      + ".input-group input {\n"
      + "  flex: 1; padding: 9px 10px; font-size: 14px;\n"
      + "  border: 1px solid #ccc; border-radius: 4px;\n"
      + "  outline: none; transition: border-color 0.15s;\n"
      + "}\n"
      + ".input-group input:focus { border-color: #1a73e8; }\n"
      + ".input-group .domain-suffix {\n"
      + "  margin-left: 6px; font-size: 13px; color: #666; white-space: nowrap;\n"
      + "}\n"
      + "input[type=text], input[type=password] {\n"
      + "  width: 100%; padding: 9px 10px; font-size: 14px;\n"
      + "  border: 1px solid #ccc; border-radius: 4px;\n"
      + "  outline: none; transition: border-color 0.15s;\n"
      + "  margin-bottom: 14px;\n"
      + "}\n"
      + "input[type=text]:focus, input[type=password]:focus { border-color: #1a73e8; }\n"
      + ".btn-primary {\n"
      + "  display: inline-block; padding: 10px 24px;\n"
      + "  background: #1a73e8; color: #fff; border: none; border-radius: 4px;\n"
      + "  font-size: 14px; font-weight: 500; cursor: pointer;\n"
      + "  transition: background 0.15s;\n"
      + "}\n"
      + ".btn-primary:hover { background: #1557b0; }\n"
      + ".btn-secondary {\n"
      + "  display: inline-block; padding: 10px 24px;\n"
      + "  background: #fff; color: #333; border: 1px solid #ccc; border-radius: 4px;\n"
      + "  font-size: 14px; font-weight: 500; cursor: pointer; margin-right: 8px;\n"
      + "}\n"
      + ".btn-secondary:hover { background: #f8f8f8; }\n"
      + ".msg { font-size: 13px; min-height: 18px; margin-bottom: 10px; }\n"
      + ".msg.error { color: #d93025; }\n"
      + ".msg.success { color: #188038; }\n"
      + ".footer-link { font-size: 13px; margin-top: 16px; text-align: center; }\n"
      + ".footer-link a { color: #1a73e8; text-decoration: none; }\n"
      + ".footer-link a:hover { text-decoration: underline; }\n"
      + ".buttons { display: flex; gap: 8px; margin-top: 8px; }\n"
      + "</style>\n";

  // =========================================================================
  // 1. Authentication (Login) Page
  // =========================================================================

  /**
   * Renders the login page.
   *
   * @param domain           the wave server domain (e.g. "example.com")
   * @param message          status message to display (may be empty)
   * @param responseType     one of "NONE", "FAILED", "SUCCESS"
   * @param disableLoginPage if true, show a disabled-auth notice instead of the form
   * @param analyticsAccount Google Analytics account ID (may be null/empty)
   */
  public static String renderAuthenticationPage(String domain, String message,
      String responseType, boolean disableLoginPage, String analyticsAccount) {
    StringBuilder sb = new StringBuilder(4096);
    sb.append("<!DOCTYPE html>\n<html dir=\"ltr\">\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append("<title>Wave in a Box login</title>\n");
    sb.append(AUTH_CSS);
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body onload=\"init()\">\n");

    sb.append("<div class=\"card\">\n");
    sb.append("  <h1>Wave in a Box</h1>\n");
    sb.append("  <div class=\"subtitle\">@").append(escapeHtml(domain)).append("</div>\n");

    if (disableLoginPage) {
      sb.append("  <p>HTTP authentication disabled by administrator. "
          + "Install and use your certificate instead.</p>\n");
    } else {
      sb.append("  <form id=\"wiab_loginform\" action=\"\" method=\"post\">\n");
      sb.append("    <label for=\"address\">Username</label>\n");
      sb.append("    <div class=\"input-group\">\n");
      sb.append("      <input type=\"text\" name=\"address\" id=\"address\" autocomplete=\"username\">\n");
      sb.append("      <span class=\"domain-suffix\">@").append(escapeHtml(domain)).append("</span>\n");
      sb.append("    </div>\n");
      sb.append("    <label for=\"password\">Password</label>\n");
      sb.append("    <input type=\"password\" name=\"password\" id=\"password\" autocomplete=\"current-password\">\n");
      sb.append("    <div class=\"msg\" id=\"messageLbl\"></div>\n");
      sb.append("    <input type=\"submit\" class=\"btn-primary\" name=\"signIn\" id=\"signIn\" value=\"Sign in\">\n");
      sb.append("  </form>\n");
      sb.append("  <div class=\"footer-link\">\n");
      sb.append("    Don't have an account? <a href=\"/auth/register\">Register</a>\n");
      sb.append("  </div>\n");
    }
    sb.append("</div>\n"); // .card

    sb.append("<script>\n");
    sb.append("var RESPONSE_STATUS_NONE = \"NONE\";\n");
    sb.append("var RESPONSE_STATUS_FAILED = \"FAILED\";\n");
    sb.append("var RESPONSE_STATUS_SUCCESS = \"SUCCESS\";\n");
    sb.append("var message = ").append(escapeJsonString(message)).append(";\n");
    sb.append("var responseType = ").append(escapeJsonString(responseType)).append(";\n");
    sb.append("function init() { setFocus(); handleResponse(responseType, message); }\n");
    sb.append("function setFocus() { var el = document.getElementById(\"address\"); if (el) el.focus(); }\n");
    sb.append("function handleResponse(rt, msg) {\n");
    sb.append("  var lbl = document.getElementById(\"messageLbl\");\n");
    sb.append("  if (!lbl) return;\n");
    sb.append("  if (rt == RESPONSE_STATUS_NONE) { lbl.style.display = \"none\"; }\n");
    sb.append("  else if (rt == RESPONSE_STATUS_FAILED) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg error\"; lbl.innerHTML = msg;\n");
    sb.append("  }\n");
    sb.append("}\n");
    sb.append("</script>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 2. User Registration Page
  // =========================================================================

  /**
   * Renders the user registration page.
   *
   * @param domain              the wave server domain
   * @param message             status message (may be empty)
   * @param responseType        one of "NONE", "FAILED", "SUCCESS"
   * @param disableRegistration if true, show a disabled notice instead of the form
   * @param analyticsAccount    Google Analytics account ID (may be null/empty)
   */
  public static String renderUserRegistrationPage(String domain, String message,
      String responseType, boolean disableRegistration, String analyticsAccount) {
    StringBuilder sb = new StringBuilder(4096);
    sb.append("<!DOCTYPE html>\n<html dir=\"ltr\">\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append("<title>Register a New Account - Wave in a Box</title>\n");
    sb.append(AUTH_CSS);
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body onload=\"init()\">\n");

    sb.append("<div class=\"card\">\n");
    sb.append("  <h1>Register</h1>\n");
    sb.append("  <div class=\"subtitle\">Create a new account @").append(escapeHtml(domain)).append("</div>\n");

    sb.append("  <div class=\"msg\" id=\"messageLbl\"></div>\n");
    sb.append("  <span id=\"loginLink\" style=\"display:none;\"> Please <a href=\"/auth/signin\">sign in</a>.</span>\n");

    if (disableRegistration) {
      sb.append("  <p>Registration disabled by administrator.</p>\n");
    } else {
      sb.append("  <form id=\"regForm\" name=\"regForm\" method=\"post\" action=\"\">\n");
      sb.append("    <label for=\"address\">Username</label>\n");
      sb.append("    <div class=\"input-group\">\n");
      sb.append("      <input type=\"text\" name=\"address\" id=\"address\" tabindex=\"1\" autocomplete=\"username\">\n");
      sb.append("      <span class=\"domain-suffix\">@").append(escapeHtml(domain)).append("</span>\n");
      sb.append("    </div>\n");
      sb.append("    <label for=\"password\">Password</label>\n");
      sb.append("    <input type=\"password\" name=\"password\" id=\"password\" tabindex=\"2\" autocomplete=\"new-password\">\n");
      sb.append("    <label for=\"verifypass\">Re-enter Password</label>\n");
      sb.append("    <input type=\"password\" name=\"verifypass\" id=\"verifypass\" tabindex=\"3\" autocomplete=\"new-password\">\n");
      sb.append("    <div class=\"buttons\">\n");
      sb.append("      <input type=\"button\" class=\"btn-secondary\" value=\"Cancel\" onclick=\"history.go(-1)\" tabindex=\"4\">\n");
      sb.append("      <input type=\"button\" class=\"btn-primary\" value=\"Register\" tabindex=\"5\" onclick=\"validate()\">\n");
      sb.append("    </div>\n");
      sb.append("  </form>\n");
    }
    sb.append("</div>\n"); // .card

    sb.append("<script>\n");
    sb.append("var RESPONSE_STATUS_NONE = \"NONE\";\n");
    sb.append("var RESPONSE_STATUS_FAILED = \"FAILED\";\n");
    sb.append("var RESPONSE_STATUS_SUCCESS = \"SUCCESS\";\n");
    sb.append("var message = ").append(escapeJsonString(message)).append(";\n");
    sb.append("var responseType = ").append(escapeJsonString(responseType)).append(";\n");
    sb.append("var domain = ").append(escapeJsonString(domain)).append(";\n");
    sb.append("function init() { setFocus(); handleResponse(responseType, message); }\n");
    sb.append("function setFocus() { var el = document.getElementById(\"address\"); if (el) el.focus(); }\n");
    sb.append("function handleResponse(rt, msg) {\n");
    sb.append("  var lbl = document.getElementById(\"messageLbl\");\n");
    sb.append("  if (!lbl) return;\n");
    sb.append("  if (rt == RESPONSE_STATUS_SUCCESS) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg success\"; lbl.innerHTML = msg;\n");
    sb.append("    document.getElementById(\"loginLink\").style.display = \"inline\";\n");
    sb.append("  } else if (rt == RESPONSE_STATUS_FAILED) {\n");
    sb.append("    lbl.style.display = \"block\"; lbl.className = \"msg error\"; lbl.innerHTML = msg;\n");
    sb.append("  }\n");
    sb.append("}\n");
    sb.append("function validate() {\n");
    sb.append("  var address = document.getElementById(\"address\").value;\n");
    sb.append("  if (address.length < 1) {\n");
    sb.append("    handleResponse(RESPONSE_STATUS_FAILED, \"Username portion of address cannot be empty\"); return;\n");
    sb.append("  }\n");
    sb.append("  if (!isAlphaNumeric(address)) {\n");
    sb.append("    handleResponse(RESPONSE_STATUS_FAILED, \"Only letters (a-z), numbers (0-9), and periods (.) are allowed in Username\"); return;\n");
    sb.append("  }\n");
    sb.append("  var password = document.getElementById(\"password\").value;\n");
    sb.append("  var verifypass = document.getElementById(\"verifypass\").value;\n");
    sb.append("  if (password != null && verifypass != null && password != verifypass) {\n");
    sb.append("    handleResponse(RESPONSE_STATUS_FAILED, \"Password and password verification do not match!\"); return;\n");
    sb.append("  }\n");
    sb.append("  document.getElementById(\"address\").value = address + \"@\" + domain;\n");
    sb.append("  document.getElementById(\"regForm\").submit();\n");
    sb.append("}\n");
    sb.append("function isAlphaNumeric(s) {\n");
    sb.append("  return s.length > 0 && s.search(/[^a-zA-Z0-9.]/g) == -1;\n");
    sb.append("}\n");
    sb.append("</script>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 3. Wave Client Page
  // =========================================================================

  /**
   * Renders the main wave client (GWT host) page.
   *
   * @param sessionJson      session object (domain, address, id_seed)
   * @param clientFlags      client flag overrides
   * @param websocketAddress the websocket host:port for the client to connect to
   * @param topBarHtml       pre-rendered top-bar HTML fragment
   * @param analyticsAccount Google Analytics account ID (may be null/empty)
   */
  public static String renderWaveClientPage(JSONObject sessionJson, JSONObject clientFlags,
      String websocketAddress, String topBarHtml, String analyticsAccount) {
    StringBuilder sb = new StringBuilder(4096);
    sb.append("<!DOCTYPE html>\n<html>\n<head>\n");
    sb.append("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
    sb.append("<title>Wave in a Box</title>\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    // Session variables
    sb.append("<script type=\"text/javascript\">\n");
    sb.append("var __session = ").append(sessionJson.toString()).append(";\n");
    sb.append("var __websocket_address = ").append(escapeJsonString(websocketAddress)).append(";\n");
    sb.append("var __client_flags = ").append(clientFlags.toString()).append(";\n");
    sb.append("</script>\n");
    // Inline styles (same as original WaveClientPage.gxp)
    sb.append("<style type=\"text/css\">\n");
    sb.append("body { margin: 0; }\n");
    sb.append(".topbar {\n");
    sb.append("  height: 32px; line-height: 32px;\n");
    sb.append("  border-bottom: solid 1px black; overflow: visible;\n");
    sb.append("  font-family: \"Gill Sans\", \"Lucida Grande\", Verdana, Arial, sans-serif;\n");
    sb.append("  font-size: 16px; padding: 0 0.5em;\n");
    sb.append("  position: relative; z-index: 1;\n");
    sb.append("}\n");
    sb.append(".logo { padding: 1px; float: left; }\n");
    sb.append(".title { float: left; margin-left: 0.5em; }\n");
    sb.append(".banner { float: left; margin-left: 0.5em; }\n");
    sb.append(".earth { padding: 4px; float: left; }\n");
    sb.append(".lang { height: 19px; }\n");
    sb.append(".domain { color: #606060; }\n");
    sb.append(".info { float: right; }\n");
    sb.append(".online { color: green; }\n");
    sb.append(".connecting { color: #ff7f00; font-weight: bold; }\n");
    sb.append(".offline { color: red; font-weight: bold; }\n");
    sb.append("</style>\n");
    // GWT stats + nocache JS
    sb.append("<script type=\"text/javascript\">\n");
    sb.append("var stats = window.__stats = [];\n");
    sb.append("window.__gwtStatsEvent = function(evt) {\n");
    sb.append("  stats[stats.length] = evt;\n");
    sb.append("  var listener = window.__stats_listener;\n");
    sb.append("  listener && listener(evt);\n");
    sb.append("  return true;\n");
    sb.append("}\n");
    sb.append("</script>\n");
    sb.append("<script type=\"text/javascript\" src=\"webclient/webclient.nocache.js\"></script>\n");
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body>\n");
    // GWT history frame
    sb.append("<iframe src=\"javascript:''\" id=\"__gwt_historyFrame\" ");
    sb.append("style=\"position:absolute;width:0;height:0;border:0\"></iframe>\n");
    // Top bar
    sb.append(topBarHtml).append("\n");
    // App container
    sb.append("<div id=\"app\" style=\"position:absolute; top:33px; right:0px; bottom:0px; left:0px;\"></div>\n");
    sb.append("<noscript>\n");
    sb.append("<div style=\"width:22em;position:absolute;left:50%;margin-left:-11em;");
    sb.append("color:red;background-color:white;border:1px solid red;padding:4px;font-family:sans-serif\">\n");
    sb.append("Your web browser must have JavaScript enabled in order for this application to display correctly.\n");
    sb.append("</div>\n");
    sb.append("</noscript>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 4. Top Bar Fragment
  // =========================================================================

  /**
   * Renders the top-bar HTML fragment shown above the wave client.
   *
   * @param username user part of the address (before @), or null if not logged in
   * @param domain   the wave server domain
   */
  public static String renderTopBar(String username, String domain) {
    StringBuilder sb = new StringBuilder(512);
    sb.append("<div class=\"topbar\">\n");
    sb.append("  <a href=\"/\"><img src=\"/static/logo.png\" alt=\"logo\" class=\"logo\"></a>\n");
    sb.append("  <div class=\"title\">Wave in a box</div>\n");
    sb.append("  <div class=\"banner\" id=\"banner\"></div>\n");
    sb.append("  <div class=\"info\">\n");
    if (username == null) {
      sb.append("    Not logged in |\n");
      sb.append("    <a href=\"/auth/register\">Register</a> |\n");
      sb.append("    <a href=\"/auth/signin?r=/\">Sign In</a>\n");
    } else {
      sb.append("    <select id=\"lang\" class=\"lang\" size=\"1\"></select> |\n");
      sb.append("    ").append(escapeHtml(username));
      sb.append("<span class=\"domain\">@").append(escapeHtml(domain)).append("</span> |\n");
      sb.append("    <span id=\"unsavedStateContainer\" style=\"width:60px\">Saved</span> |\n");
      sb.append("    <span id=\"netstatus\" class=\"offline\">Offline</span> |\n");
      sb.append("    <a id=\"signout\" href=\"/auth/signout?r=/\">Sign out</a>\n");
    }
    sb.append("  </div>\n");
    sb.append("</div>");
    return sb.toString();
  }

  // =========================================================================
  // 5. Robot Registration Page
  // =========================================================================

  /**
   * Renders the robot registration form page.
   *
   * @param domain           the wave server domain
   * @param message          status/error message (may be empty)
   * @param analyticsAccount Google Analytics account ID (may be null/empty)
   */
  public static String renderRobotRegistrationPage(String domain, String message,
      String analyticsAccount) {
    StringBuilder sb = new StringBuilder(2048);
    sb.append("<!DOCTYPE html>\n<html>\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<title>Robot Registration</title>\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append(AUTH_CSS);
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body>\n");
    sb.append("<div class=\"card\">\n");
    sb.append("  <h1>Robot Registration</h1>\n");
    if (message != null && !message.isEmpty()) {
      sb.append("  <p><b>").append(escapeHtml(message)).append("</b></p>\n");
    }
    sb.append("  <form method=\"post\" action=\"\">\n");
    sb.append("    <label for=\"username\">Robot Username</label>\n");
    sb.append("    <div class=\"input-group\">\n");
    sb.append("      <input type=\"text\" name=\"username\" id=\"username\">\n");
    sb.append("      <span class=\"domain-suffix\">@").append(escapeHtml(domain)).append("</span>\n");
    sb.append("    </div>\n");
    sb.append("    <label for=\"location\">Robot URL</label>\n");
    sb.append("    <input type=\"text\" name=\"location\" id=\"location\">\n");
    sb.append("    <input type=\"submit\" class=\"btn-primary\" value=\"Register\">\n");
    sb.append("  </form>\n");
    sb.append("</div>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 6. Robot Registration Success Page
  // =========================================================================

  /**
   * Renders the page shown after successful robot registration.
   *
   * @param token            the consumer token (robot address)
   * @param tokenSecret      the consumer token secret
   * @param analyticsAccount Google Analytics account ID (may be null/empty)
   */
  public static String renderRobotRegistrationSuccessPage(String token, String tokenSecret,
      String analyticsAccount) {
    StringBuilder sb = new StringBuilder(2048);
    sb.append("<!DOCTYPE html>\n<html>\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<title>Robot Successfully Registered</title>\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append(AUTH_CSS);
    appendAnalyticsFragment(sb, analyticsAccount, null);
    sb.append("</head>\n<body>\n");
    sb.append("<div class=\"card\">\n");
    sb.append("  <h1>Robot Registered</h1>\n");
    sb.append("  <p>Your robot has been successfully registered. Please take note of the consumer\n");
    sb.append("  token and token secret to use for the Active API.</p>\n");
    sb.append("  <table>\n");
    sb.append("    <tr><td><b>Consumer Token</b></td><td>").append(escapeHtml(token)).append("</td></tr>\n");
    sb.append("    <tr><td><b>Consumer Token Secret</b></td><td>").append(escapeHtml(tokenSecret)).append("</td></tr>\n");
    sb.append("  </table>\n");
    sb.append("</div>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 7. OAuth Authorize Token Page
  // =========================================================================

  /**
   * Renders the OAuth token authorization page.
   *
   * @param user      the logged-in user address
   * @param xsrfToken XSRF protection token
   */
  public static String renderOAuthAuthorizeTokenPage(String user, String xsrfToken) {
    StringBuilder sb = new StringBuilder(2048);
    sb.append("<!DOCTYPE html>\n<html>\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<title>Authorization Required</title>\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append(AUTH_CSS);
    sb.append("</head>\n<body>\n");
    sb.append("<div class=\"card\">\n");
    sb.append("  <h1>Authorization Required</h1>\n");
    sb.append("  <p>You are logged in as <b>").append(escapeHtml(user)).append("</b>.</p>\n");
    sb.append("  <p>A program would like to access your waves and perform operations on your behalf.</p>\n");
    sb.append("  <form method=\"post\" action=\"\">\n");
    sb.append("    <input type=\"hidden\" name=\"token\" value=\"").append(escapeHtml(xsrfToken)).append("\">\n");
    sb.append("    <div class=\"buttons\">\n");
    sb.append("      <input type=\"submit\" class=\"btn-primary\" value=\"Agree\" name=\"agree\">\n");
    sb.append("      <input type=\"submit\" class=\"btn-secondary\" value=\"Cancel\" name=\"cancel\">\n");
    sb.append("    </div>\n");
    sb.append("  </form>\n");
    sb.append("</div>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 8. OAuth Authorization Code Page
  // =========================================================================

  /**
   * Renders the page that displays an OAuth authorization code.
   *
   * @param code the authorization code to show
   */
  public static String renderOAuthAuthorizationCodePage(String code) {
    StringBuilder sb = new StringBuilder(1024);
    sb.append("<!DOCTYPE html>\n<html>\n<head>\n");
    sb.append("<meta charset=\"UTF-8\">\n");
    sb.append("<title>Authorization code</title>\n");
    sb.append("<link rel=\"shortcut icon\" href=\"/static/favicon.ico\">\n");
    sb.append(AUTH_CSS);
    sb.append("</head>\n<body>\n");
    sb.append("<div class=\"card\">\n");
    sb.append("  <h1>Authorization Code</h1>\n");
    sb.append("  <p>Please copy this code, switch to your application and paste it there:</p>\n");
    sb.append("  <input id=\"code\" type=\"text\" readonly ");
    sb.append("style=\"width:100%;font-family:monospace;\" ");
    sb.append("onclick=\"this.focus();this.select();\" ");
    sb.append("value=\"").append(escapeHtml(code)).append("\">\n");
    sb.append("</div>\n");
    sb.append("</body>\n</html>\n");
    return sb.toString();
  }

  // =========================================================================
  // 9. Analytics Fragment (private helper)
  // =========================================================================

  /**
   * Appends the Google Analytics tracking script if an account is configured.
   *
   * @param sb      the builder to append to
   * @param account the GA account ID (may be null or empty)
   * @param error   optional custom-variable error string (may be null)
   */
  private static void appendAnalyticsFragment(StringBuilder sb, String account, String error) {
    if (account == null || account.isEmpty()) {
      return;
    }
    sb.append("<script type=\"text/javascript\">\n");
    sb.append("var _gaq = _gaq || [];\n");
    sb.append("_gaq.push(['_setAccount', ").append(escapeJsonString(account)).append("]);\n");
    if (error != null && !error.isEmpty()) {
      sb.append("_gaq.push(['_setCustomVar', 1, 'error', ").append(escapeJsonString(error)).append(", 3]);\n");
    }
    sb.append("_gaq.push(['_trackPageview']);\n");
    sb.append("(function() {\n");
    sb.append("  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\n");
    sb.append("  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n");
    sb.append("  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\n");
    sb.append("})();\n");
    sb.append("</script>\n");
  }

  // =========================================================================
  // HTML / JSON escaping helpers
  // =========================================================================

  /**
   * Escapes a string for safe inclusion in HTML content or attribute values.
   * Handles the five XML special characters: {@code & < > " '}.
   *
   * @param s the raw string (may be null)
   * @return the escaped string, or empty string if null
   */
  public static String escapeHtml(String s) {
    if (s == null) return "";
    StringBuilder sb = new StringBuilder(s.length() + 16);
    for (int i = 0; i < s.length(); i++) {
      char c = s.charAt(i);
      switch (c) {
        case '&':  sb.append("&amp;");  break;
        case '<':  sb.append("&lt;");   break;
        case '>':  sb.append("&gt;");   break;
        case '"':  sb.append("&quot;"); break;
        case '\'': sb.append("&#39;");  break;
        default:   sb.append(c);
      }
    }
    return sb.toString();
  }

  /**
   * Wraps a string as a JSON string literal (with surrounding quotes), escaping
   * special characters. Returns {@code "null"} (unquoted) for null input.
   *
   * @param s the raw string (may be null)
   * @return a JSON string literal, e.g. {@code "hello \"world\""}
   */
  public static String escapeJsonString(String s) {
    if (s == null) return "null";
    StringBuilder sb = new StringBuilder(s.length() + 16);
    sb.append('"');
    for (int i = 0; i < s.length(); i++) {
      char c = s.charAt(i);
      switch (c) {
        case '"':  sb.append("\\\""); break;
        case '\\': sb.append("\\\\"); break;
        case '\n': sb.append("\\n");  break;
        case '\r': sb.append("\\r");  break;
        case '\t': sb.append("\\t");  break;
        case '/':  sb.append("\\/");  break;
        default:
          if (c < 0x20) {
            sb.append(String.format("\\u%04x", (int) c));
          } else {
            sb.append(c);
          }
      }
    }
    sb.append('"');
    return sb.toString();
  }
}
