package org.waveprotocol.box.j2cl.common;

/**
 * Build-generated flag class — do not edit by hand.
 *
 * Generated by maven-resources-plugin (filtering) from
 * src/main/java-templates; the literal boolean value is substituted at
 * generate-sources time so that DEBUG_OVERLAY_ENABLED is a true Java
 * compile-time constant (JLS §4.12.4).  This allows the Closure compiler to
 * perform dead-code elimination on all guarded branches during
 * ADVANCED_OPTIMIZATIONS.
 *
 * Production builds: DEBUG_OVERLAY_ENABLED = false
 * Dev / sandbox builds: DEBUG_OVERLAY_ENABLED = true
 */
public final class J2clDebugFlags {

    /**
     * Compile-time constant controlling debug-only overlay tagging.
     * When false, calls to markDebugOnly() are no-ops and the Closure compiler
     * eliminates the tagging logic and associated debug strings from the bundle.
     */
    public static final boolean DEBUG_OVERLAY_ENABLED = ${j2cl.debug.overlay.enabled};
}
